### ISSUE TITLE
led option doesn't work (no led)

### ISSUE THREAD

**Issue by rsalvignac** [katzer/cordova-plugin-local-notifications#1486] opened 2018-01-02 21:40 UTC
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9.0-beta 1
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Samsung Galaxy tab A
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```): Android 6.3.0
* Plugin config
* Ionic Version (if using Ionic) none

## Expected Behavior

The led indicator doesn't work. We should have led blinking.

## Actual Behavior

We should have led blinking.

## Steps to Reproduce

This is my code :
```
	cordova.plugins.notification.local.schedule(
	{
		id: 1,
		at: new Date(),
		title: 'Oxiva Mobile',
		text: 'Ceci est une notification',
		foreground: true,
		vibrate: true,
		led: { color: '#FF00FF', on: 500, off: 500 }
		//badge: 0,
	});
```

## Context
I'm trying to make local notifications with custom led blinking

## Debug logs
none
  * Android: $ adb logcat

**Comment by katzer** [comment] 2018-01-04 16:10
Actually I dont have a device with LED. Thats why I cannot test it. If there's a bug, any PR or hint is welcome.

**Comment by katzer** [comment] 2018-01-04 16:11
It might be possible that the permission is not granted...

**Comment by rsalvignac** [comment] 2018-01-05 14:44
I've tested with the code below

I'think it's not a permission problem.

```
    cordova.plugins.notification.local.requestPermission(function (granted) 
    {
        alert(granted);
    	cordova.plugins.notification.local.schedule(
    	{
    		id: 1,
    		at: new Date(),
    		title: 'Oxiva Mobile',
    		text: 'Ceci est une notification',
    		foreground: true,
    		vibrate: true,
    		led: { color: '#FF00FF', on: 500, off: 500 },
    		//badge: 0,
    	});
    });
```
alert(granted); returns true

**Comment by katzer** [comment] 2018-01-06 13:20
@rsalvignac I mean permission to show LED lights if there's a permission for.

**Comment by rsalvignac** [comment] 2018-01-08 09:21
I've searched this permission but didn't found it.

**Comment by katzer** [comment] 2018-01-09 12:54
@rsalvignac are you able to debug this yourself and submit a PR?

**Comment by katzer** [comment] 2018-02-12 13:19
Hi, I got a new dev phone with LED and I run your code with success. So I am closing this here. The led option works.

**Closed by katzer** 2018-02-12 13:19 UTC
Labels: android, bug

**Comment by brittonk** [comment] 2018-02-15 06:30
I have the same problem. When I set the LED option, the same way you have and the instructions suggest, the notification breaks and does not come thru.

Testing on Galaxy S6 Edge.

**Comment by rwillett** [comment] 2018-02-15 08:01
Suggest you open a new issue with your exact situation. Saying me too isn't helpful as you have different plugin versions, different SDK's, different versions of Android, different versions of Android from Samsung, different code etc etc.

**Comment by brittonk** [comment] 2018-02-15 08:12
It was intended to be helpful to the op not for the development. Stating
that if he avoids the recommended setting on the tutorial and just uses the
color he may get a functioning led.

**Comment by rwillett** [comment] 2018-02-15 08:18
OK, it didn;t read like that. I suggest you then do a PR for the tutorial.

**Comment by katzer** [comment] 2018-02-16 13:45
@brittonk For me both ways work as expected.

**Comment by HossamBhi** [comment] 2019-08-14 19:02
i have same problem only screen flash but led don't work
