### ISSUE TITLE
Incompatibility with Firebase plugin (iOS)

### ISSUE THREAD

**Issue by ThomasKientz** [katzer/cordova-plugin-local-notifications#1373] opened 2017-08-31 13:00 UTC
It appears that using this plugin aside of the [firebase plugin](https://github.com/arnesson/cordova-plugin-firebase) causes notifications not to be triggered on iOS :

Sometimes, depending on the implementations and order of plugin installations (weird..) or other  :

- Native notifications banners are no more showing up (when app is in foreground)
- On('trigger') doesn't triggered.
- Notifications are not triggered at ALL (background or foreground). 

The firebase plugin also make use notification systems with firebase cloud messaging (FCM).

I guess there is an incompatibility between those two plugins installed.

It was very a headache figuring this out, i'm try with master branch and branch "x".

Seems to work as expected on Android.

**Comment by flache** [comment] 2017-09-04 12:00
I am running into the same issue. Is there a fix?

**Comment by ThomasKientz** [comment] 2017-09-04 12:13
I'm still stuck. I've noticed during my tests that I can have more results with the "x" branch. I remember, I have succeed to have the .on("trigger") method working aside with firebase. But for the moment nothing works at my side (no trigger, no foreground or background notifications, nothing).

**Comment by Menardi** [comment] 2017-09-05 14:26
I'm having the same problem, I think it is an issue with Firebase as per https://groups.google.com/forum/#!topic/firebase-talk/xeaU6V0-s4c. It's fixed in the 4.0 SDK, which presumably cordova-plugin-firebase is not using. I couldn't quite figure out what version it's currently on, but if it's pre-4.0, that could be the cause.

**Comment by flache** [comment] 2017-09-05 23:06
I tried again today with the x-branch and it works well so far

Just keep in mind that `cordova.plugins.notification.local.registerPermission()` was refactored to `cordova.plugins.notification.local.requestPermission()` and you need to set the `trigger` property instead of `at` on the notification objects to the desired date object.

I did not find the changes in the x branch documented anywhere other than in the source code

**Comment by ThomasKientz** [comment] 2017-09-06 08:09
@flache x branch doesn't work me for alongside with firebase. Which firebase plugin are you using ([FCM](https://github.com/fechanique/cordova-plugin-fcm), [firebase](https://github.com/arnesson/cordova-plugin-firebase), other) ? Can you share your config and plugin list please ?

Are foreground notifications (with the ios banner) working too ?

Weird thing now is that even if i have no firebase plugin installed (even after a platform remove then add). The master branch doesn't work at all. I must use the x branch...

**Comment by flache** [comment] 2017-09-06 08:18
The relevant parts of my `config.xml`

```xml
  <plugin name="phonegap-plugin-push" spec="~2.0.0-rc5"/>
  <plugin name="cordova-plugin-local-notifications"
          spec="https://github.com/katzer/cordova-plugin-local-notifications.git#x"/>
```

Like I said, I am also using the x branch of this repository.
As fcm plugin I am using [`phonegap-plugin-push`](https://github.com/phonegap/phonegap-plugin-push) @2.0.0-rc5. I realized that there is already the 2.0.0 version available but as long as nothing breaks I keep the RC.

iOS Banners show even if the app is in foreground. As a side note, my understanding is that this is not the intended behaviour by iOS, so I would be happier if the banner didn't pop up when the app is in foreground, but it is tolerable in my situation.

**Comment by katzer** [comment] 2017-09-06 14:59
@ThomasKientz It will take time before I can look into.

As you have noticed I am working on a new release (x branch). If you are already using the branch be aware that the doc is out of date, there might  be future changes, haven't touched Android yet, ...

**Comment by katzer** [comment] 2017-09-06 15:01
@flache 

> I would be happier if the banner didn't pop up when the app is in foreground

You can use `schedule({ text: 'Pops up only in background', silent: true, ... })` to avoid that.

**Comment by GunslingerBara** [comment] 2017-10-11 21:41
I am running into this problem. Is there any solution yet?

**Comment by OliverZiegler** [comment] 2017-11-08 16:13
This not only seems to occur with firebase-plugin but also with [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push).

As @Menardi said using `UNUserNotificationCenter` will result in not calling 'application:didReceiveNotification` on iOS.

To give the choices to the developer, couldn't we remove 
    if ([toast.trigger isKindOfClass:UNPushNotificationTrigger.class])
        return;
from `AppLocalNotification.m` in line 509 and deliver EVERY received notification to the "trigger"-Event?
This way we can also show some toasts for eg. PushNotifications if developers want to in the on('trigger') event callback.

**Comment by thefolenangel** [comment] 2017-11-09 13:34
Hm.
Is this the reason, why I dont see a a notification in my list?
I am using phonegap-plugin-push @ 1.10.5

What happens is: 
production app *with 0.8.5* , notifications work as supposed in foreground (i am using custom sound), however if my app is background mode, i only get notification and no sound.

I decided to try the new version 0.90beta, in it i have the same problem with the background as above, however now on the foreground sound is played, but no notification is showed. in the console i attache on trigger to see if the notification is triggered, and it is. I can see it.

**Comment by katzer** [comment] 2017-11-09 13:44
@thefolenangel Can you post the code here.

**Comment by katzer** [comment] 2017-11-09 13:57
Without any push plugins my device plays a custom sound even the device is locked or app isn't running or in background.

**Comment by katzer** [comment] 2017-11-09 13:58
Does the notification come from phonegap-plugin-push or cordova-plugin-local-notifications?

**Comment by thefolenangel** [comment] 2017-11-09 14:20
Sadly I can't post any code, since its proprietary . But I will try to explain as much as I can.

My app is map based, used both foreground and in background (user preference). What we do is, we get information from the server (regardless of backgroud) we measure distance, if its close to me I fire a cordova.plugin.notification.local.schedule with text and so forth.

The push plugin is used when you log in and someotimes we fire notifications, based on user preference. For example the user said I would like to know before tommorrow if there are any obstacles on my road. Then is when I use phonegap-push-plugin.

This are all the plugins we use. Cordova-ios is 4.4.0

com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
com.mediamatrixdoo.keepscreenon 1.0.1 "KeepScreenOn"
com.phonegap.plugins.nativesettingsopener 1.2 "Native settings"
cordova-background-geolocation-lt 2.7.0 "BackgroundGeolocation"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-background-fetch 4.0.4 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.6.6-dev "BackgroundMode"
cordova-plugin-badge 0.8.5 "Badge"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-local-notifications 0.9.0-beta.0 "LocalNotification"
cordova-plugin-media 2.4.1 "Media"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 1.3.0 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-vibration 2.1.2 "Vibration"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova.plugins.diagnostic 3.2.1 "Diagnostic"
phonegap-plugin-push 1.10.5 "PushPlugin" 

So I decided to test this. I created a function which is called everytime you switch between background mode and foreground mode (my idea was since the problem is happening in the background mode, let me test if it will schedule notifications properly). Additionally I attached on trigger  and click listener.

This is the log from there.
//starting Background mode
2017-11-09 14:50:00.712530+0100 MyAppName[433:77023] bgGeo onlocation 
2017-11-09 14:50:00.839746+0100 MyAppName[433:77933] TIC Read Status [5:0x0]: 1:57 
2017-11-09 14:50:00.840316+0100 MyAppName[433:77933] TIC Read Status [5:0x0]: 1:57 
2017-11-09 14:50:05.636591+0100 MyAppName[433:77023] - TSBackgroundFetch removeListener: TSLocationManager 
2017-11-09 14:50:05.638256+0100 MyAppName[433:77023] THREAD WARNING: ['BackgroundGeolocation'] took '20.580078' ms. Plugin should use a background thread. 

//Stopping Background

2017-11-09 14:50:05.638473+0100 MyAppName[433:77023] in switch Background Foreground || 
2017-11-09 14:50:05.768383+0100 MyAppName[433:77023] active 
2017-11-09 14:50:05.768473+0100 MyAppName[433:77023] PushPlugin skip clear badge 
2017-11-09 14:50:06.237977+0100 MyAppName[433:77023] -- Notification trigger---testthis is generated at Thu Nov 09 2017 14:50:05 GMT+0100 (CET) 

//generates notification but JUST sound
//start Background mode

2017-11-09 14:50:12.209321+0100 MyAppName[433:77931] - TSBackgroundFetch addListener: TSLocationManager 
2017-11-09 14:50:12.215338+0100 MyAppName[433:77931] - TSBackgroundFetch started 
2017-11-09 14:50:12.447633+0100 MyAppName[433:77023] bgGeo onlocation 
2017-11-09 14:50:12.644761+0100 MyAppName[433:77931] TIC Read Status [9:0x0]: 1:57 
2017-11-09 14:50:12.645160+0100 MyAppName[433:77931] TIC Read Status [9:0x0]: 1:57 
2017-11-09 14:50:12.952789+0100 MyAppName[433:77023] - TSBackgroundFetch removeListener: TSLocationManager 
2017-11-09 14:50:12.954241+0100 MyAppName[433:77023] THREAD WARNING: ['BackgroundGeolocation'] took '20.723877' ms. Plugin should use a background thread. 
2017-11-09 14:50:12.954405+0100 MyAppName[433:77023] in switch Background Foreground || 
2017-11-09 14:50:12.966763+0100 MyAppName[433:77023] THREAD WARNING: ['Geolocation'] took '12.189941' ms. Plugin should use a background thread. 
2017-11-09 14:50:13.184257+0100 MyAppName[433:77023] active 
2017-11-09 14:50:13.184345+0100 MyAppName[433:77023] PushPlugin skip clear badge 
2017-11-09 14:50:13.203472+0100 MyAppName[433:77023] -- Notification trigger---testthis is generated at Thu Nov 09 2017 14:50:12 GMT+0100 (CET) 

//Generates normal notification with sound and with notification in my notification list 

2017-11-09 14:50:18.801090+0100 MyAppName[433:78078] - TSBackgroundFetch addListener: TSLocationManager 
2017-11-09 14:50:18.809582+0100 MyAppName[433:78078] - TSBackgroundFetch started 
2017-11-09 14:50:19.052036+0100 MyAppName[433:77023] bgGeo onlocation 
2017-11-09 14:50:19.067123+0100 MyAppName[433:77023] THREAD WARNING: ['BackgroundGeolocation'] took '14.972900' ms. Plugin should use a background thread. 
2017-11-09 14:50:19.067696+0100 MyAppName[433:77023] bgGeo onlocation 
2017-11-09 14:50:19.236000+0100 MyAppName[433:78171] TIC Read Status [13:0x0]: 1:57 
2017-11-09 14:50:19.236093+0100 MyAppName[433:78171] TIC Read Status [13:0x0]: 1:57 

//I click on the notification in the notification list.

2017-11-09 14:50:23.306188+0100 MyAppName[433:77023] - TSBackgroundFetch removeListener: TSLocationManager 
2017-11-09 14:50:23.307659+0100 MyAppName[433:77023] THREAD WARNING: ['BackgroundGeolocation'] took '23.443848' ms. Plugin should use a background thread. 
2017-11-09 14:50:23.307821+0100 MyAppName[433:77023] in switch Background Foreground || 
2017-11-09 14:50:23.321093+0100 MyAppName[433:77023] THREAD WARNING: ['Geolocation'] took '13.093750' ms. Plugin should use a background thread. 
2017-11-09 14:50:23.363292+0100 MyAppName[433:77023] -- Notification click---test 
//generates click event
2017-11-09 14:50:23.601709+0100 MyAppName[433:77023] active 
2017-11-09 14:50:23.602671+0100 MyAppName[433:77023] PushPlugin skip clear badge 
2017-11-09 14:50:28.439847+0100 MyAppName[433:78078] - TSBackgroundFetch addListener: TSLocationManager 
2017-11-09 14:50:28.450592+0100 MyAppName[433:78078] - TSBackgroundFetch started 
2017-11-09 14:50:28.712365+0100 MyAppName[433:77023] bgGeo onlocation 
2017-11-09 14:50:28.951779+0100 MyAppName[433:78166] TIC Read Status [17:0x0]: 1:57 
2017-11-09 14:50:28.952313+0100 MyAppName[433:78166] TIC Read Status [17:0x0]: 1:57 
2017-11-09 14:50:29.098805+0100 MyAppName[433:77023] - TSBackgroundFetch removeListener: TSLocationManager 
2017-11-09 14:50:29.100780+0100 MyAppName[433:77023] THREAD WARNING: ['BackgroundGeolocation'] took '19.365967' ms. Plugin should use a background thread. 
2017-11-09 14:50:29.100995+0100 MyAppName[433:77023] in switch Background Foreground || 

//Doesn’t generate notification at all, not event sound.

2017-11-09 14:50:29.284115+0100 MyAppName[433:77023] active 
2017-11-09 14:50:29.284204+0100 MyAppName[433:77023] PushPlugin skip clear badge 
2017-11-09 14:50:36.059199+0100 MyAppName[433:78267] - TSBackgroundFetch addListener: TSLocationManager 
2017-11-09 14:50:36.071178+0100 MyAppName[433:78267] - TSBackgroundFetch started 
2017-11-09 14:50:36.337717+0100 MyAppName[433:77023] bgGeo onlocation 
2017-11-09 14:50:36.594771+0100 MyAppName[433:78354] TIC Read Status [21:0x0]: 1:57 
2017-11-09 14:50:36.595196+0100 MyAppName[433:78354] TIC Read Status [21:0x0]: 1:57 
2017-11-09 14:50:38.617991+0100 MyAppName[433:77023] - TSBackgroundFetch removeListener: TSLocationManager 
2017-11-09 14:50:38.620143+0100 MyAppName[433:77023] THREAD WARNING: ['BackgroundGeolocation'] took '16.892822' ms. Plugin should use a background thread. 
2017-11-09 14:50:38.620367+0100 MyAppName[433:77023] in switch Background Foreground || 
2017-11-09 14:50:38.632791+0100 MyAppName[433:77023] THREAD WARNING: ['Geolocation'] took '12.221924' ms. Plugin should use a background thread. 
2017-11-09 14:50:38.832388+0100 MyAppName[433:77023] active 
2017-11-09 14:50:38.832480+0100 MyAppName[433:77023] PushPlugin skip clear badge 
2017-11-09 14:50:39.203582+0100 MyAppName[433:77023] -- Notification trigger---testthis is generated at Thu Nov 09 2017 14:50:38 GMT+0100 (CET) 

//just sound notification.

2017-11-09 14:50:47.877012+0100 MyAppName[433:78270] - TSBackgroundFetch addListener: TSLocationManager 
2017-11-09 14:50:47.882341+0100 MyAppName[433:78270] - TSBackgroundFetch started

my switch method contains

console.log("in switch Background Foreground || ");
    var notiDate = new Date();
    var texttex = "this is generated at " + notiDate;
    cordova.plugins.notification.local.schedule({
                                                id:1,
                                                title: "test",
                                                text: texttex,
                                                sound:"file://mp3/custom.mp3",
                                                trigger:{at: notiDate}
                                                });

**Comment by katzer** [comment] 2017-11-09 15:08
@thefolenangel In case of iOS I would be careful using `.mp3` audio formats.

See here for more info: https://developer.apple.com/documentation/usernotifications/unnotificationsound

```js
cordova.plugins.notification.local.schedule({
    title: "test",
    text: "texttext",
    foreground: true,
    sound: "file://sound/custom.caf",  // => You will end up using different audio files for iOS and Android
    trigger:{ at: new Date() }
});
```

---

You may have noticed that 0.9-beta supports location based trigger on iOS.

**Comment by tzappia** [comment] 2017-11-16 16:33
I am also seeing this issue using both cordova-plugin-firebase and cordova-plugin-local-notification. The local notifications do not display when the app is in the foreground. Can anyone else who has looked at this issue so far point me in a good direction to look at this further? I'm using the latest from master for cordova-plugin-local-notification as of the time of this post.

**Comment by Menardi** [comment] 2017-11-21 01:55
Using the latest code from master, this issue appears to be fixed for me, using it alongside `cordova-plugin-firebase`. Thanks for your work, @katzer!

**Comment by tzappia** [comment] 2017-11-21 15:06
@Menardi would you be kind enough to post the versions you've combined to see this work because it would certainly be helpful to me (and I'm sure others!)
cordova-cli:
cordova-ios:
cordova-plugin-firebase:
cordova-plugin-local-notifications:
iOS:

**Comment by GunslingerBara** [comment] 2017-11-21 19:05
@Menardi Yes please, I would love to know which versions you have that allows local notifications to work!

**Comment by Menardi** [comment] 2017-11-26 07:00
@tzappia @GunslingerBara 

I'm pretty much using the latest verson of everything. However, I haven't tested foreground notifications, which appears to be the problem you're having from your previous comment. I have only tested background notifications set relatively far in the future (~1-4 weeks).

Here are the versions you requested, in case they may be useful:
cordova-cli: 7.1.0
cordova-ios: 4.5.4
cordova-plugin-firebase: 0.1.24
cordova-plugin-local-notifications: commit d5c0072cf313ea92a496040882e11e7f36c6f916
iOS: 11.1

**Comment by fdmartins** [comment] 2017-11-28 03:26
comment the "return" and the if in line 540 in APPLocalNotification.m file; 
explain here:
https://groups.google.com/forum/#!topic/firebase-talk/xeaU6V0-s4c

**Comment by fdmartins** [comment] 2017-11-28 03:36
Aahh, and change the config.xml like this:

    <feature name="LocalNotification">
        <param name="ios-package" value="APPLocalNotification" />
        <param name="onload" value="true" />
    </feature>

**Comment by markterrill** [comment] 2017-12-06 00:47
@fdmartins are you able to provide your code?
Are you referring to commenting out the entire if in:
```
/**
 * Inform if the app has the permission to show
 * badges and local notifications.
 */
- (void) hasPermission:(CDVInvokedUrlCommand*)command
{
    if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"10.0")) {
        [self.commandDelegate runInBackground:^{
            [self.center getNotificationSettingsWithCompletionHandler:^(UNNotificationSettings* settings) {
                BOOL authorized = settings.authorizationStatus == UNAuthorizationStatusAuthorized;
                BOOL enabled = settings.notificationCenterSetting == UNNotificationSettingEnabled;
                BOOL permitted = authorized && enabled;
                CDVPluginResult* result;

                result = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK
                                             messageAsBool:permitted];

                [self.commandDelegate sendPluginResult:result
                                            callbackId:command.callbackId];
            }];
        }];
    } else {
        [self.commandDelegate runInBackground:^{
            CDVPluginResult* result;
            BOOL hasPermission;

            hasPermission = [self.app hasPermissionToScheduleLocalNotifications];

            result = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK
                                         messageAsBool:hasPermission];

            [self.commandDelegate sendPluginResult:result
                                        callbackId:command.callbackId];
        }];
    }
}
```

?

**Comment by fdmartins** [comment] 2017-12-08 14:05
- (void) userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
withCompletionHandler:(void (^)(void))completionHandler
{
UNNotificationRequest* toast = response.notification.request;
completionHandler();
/* >>>>>> I solved my problem, commenting this block;
if ([toast.trigger isKindOfClass:UNPushNotificationTrigger.class])
return;
*/
NSMutableDictionary* data = [[NSMutableDictionary alloc] init];
NSString* action = response.actionIdentifier;
NSString* event = action;
if ([action isEqualToString:UNNotificationDefaultActionIdentifier]) {
event = @"click";
} else
if ([action isEqualToString:UNNotificationDismissActionIdentifier]) {
event = @"clear";
}
if (!deviceready && [event isEqualToString:@"click"]) {
_launchDetails = @[toast.options.id, event];
}
if (![event isEqualToString:@"clear"]) {
[self fireEvent:@"clear" notification:toast];
}
if ([response isKindOfClass:UNTextInputNotificationResponse.class]) {
[data setObject:((UNTextInputNotificationResponse*) response).userText
forKey:@"text"];
}
[self fireEvent:event notification:toast data:data];
}

2017-12-05 22:47 GMT-02:00 Mark <notifications@github.com>:

**Comment by prashant37** [comment] 2018-01-10 21:35
I found one solution...run this once `window.FirebasePlugin.grantPermission();` after installation of app but for that instance local notification wont work...after that dont run this command again and both of them will start working

**Comment by katzer** [comment] 2018-01-11 08:41
@fdmartins 

>  and change the config.xml like this:
```xml
<feature name="LocalNotification">
    <param name="ios-package" value="APPLocalNotification" />
    <param name="onload" value="true" />
</feature>
```

What's the reason for?

**Comment by katzer** [comment] 2018-02-12 13:42
I made some code changes regarding this issue in the last time and I hope that it might help. Ensure to install the plugin from master branch if you wanna test the changes. I am closing this for now - Please re-open if its still an issue. Thanks!

**Closed by katzer** 2018-02-12 13:42 UTC

**Comment by ourarash** [comment] 2018-04-18 16:38
@prashant37  suggestion to not run `window.FirebasePlugin.grantPermission(); ` didn't fully work: after doing this, I only get remote notifications  when the app is in the background. When it is in the foreground, I don't receive anything, i.e., even the payload of the notification doesn't arrive, so I can't hand it off to the local notification.
