### ISSUE TITLE
Getting error when I try to build after using this plugin

### ISSUE THREAD

**Issue by mpadmaraj** [katzer/cordova-plugin-local-notifications#1577] opened 2018-04-14 04:59 UTC
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:0.9.0-beta.2
* Platform:Android
* OS version:Mac
* Device manufacturer / model:
* Cordova version (```cordova -v```):7.1.0
* Cordova platform version (```cordova platform ls```):android 6.2.3
* Plugin config
* Ionic Version (if using Ionic):2.2.2

## Expected Behavior

_Tell us what should happen_
I installed the plugin using instructions given here: https://ionicframework.com/docs/native/local-notifications/
When I run the build I get below error
## Actual Behavior

_Tell us what happens instead_

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:25: error: cannot find symbol

import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:32: error: package android.support.v4.media.app.NotificationCompat does not exist

import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:43: error: cannot find symbol

import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol

        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol

        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol

        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^

  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:120: error: cannot find symbol

        channel = new NotificationChannel(
                      ^

  symbol:   class NotificationChannel
  location: class Manager

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:130: error: cannot find symbol
                .setChannelId(options.getChannel())
                ^

  symbol:   method setChannelId(String)
  location: class Builder

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:296: error: cannot find symbol

        MediaStyle style;
        ^
  symbol:   class MediaStyle
  location: class Builder

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:298: error: cannot find symbol
        style = new MediaStyle(builder)

                    ^
  symbol:   class MediaStyle
  location: class Builder

/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:417: error: constructor Builder in class Builder cannot be applied to given types;

            builder = new NotificationCompat.Builder(context, options.getChannel());
                      ^
  required: Context
  found: Context,String

  reason: actual and formal argument lists differ in length

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

11 errors

:compileReleaseJavaWithJavac 
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.

> 
Compilation failed; see the compiler error output for details.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.407 secs

Error: /my-project/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:25: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:32: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:43: error: cannot find symbol
import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:120: error: cannot find symbol
        channel = new NotificationChannel(
                      ^
  symbol:   class NotificationChannel
  location: class Manager
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:130: error: cannot find symbol
                .setChannelId(options.getChannel())
                ^
  symbol:   method setChannelId(String)
  location: class Builder
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:296: error: cannot find symbol
        MediaStyle style;
        ^
  symbol:   class MediaStyle
  location: class Builder
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:298: error: cannot find symbol
        style = new MediaStyle(builder)
                    ^
  symbol:   class MediaStyle
  location: class Builder
/my-project/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:417: error: constructor Builder in class Builder cannot be applied to given types;
            builder = new NotificationCompat.Builder(context, options.getChannel());
                      ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Install the @ionic-native/local-notification
  2. run ionic build

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by victorwpbastos** [comment] 2018-04-23 21:46
Same error here.

**Comment by Tawpie** [comment] 2018-05-21 17:12
Looking very closely at the OP's error messages, there's a problem with the import statement. This is different than what I'm running into (although my errors happen at the same place) so I'll not hijack this thread.

**Comment by Gamerakki** [comment] 2018-05-25 10:53
Hi @Tawpie  @katzer @rwillett 
I tried your configuration of using 
cordova version: 7.1.0 
android platform version: 6.3.0 

Still i am facing the same issue the plugin works perfectly in ios but in android the build fails giving same error above in the issue created. It would be help if any fix is provide. Waiting for an feedback from you guys

**Comment by Tawpie** [comment] 2018-05-25 15:15
@Gamerakki My error was slightly different than yours. You're seeing the first error at the start of the import statement (which may be related to your node packages). My error was that the NotificationChannel property of android.app was undefined (pointing to a problem with the sdk, either it's not up to date or is broken).

To get mine to work (it's working on two systems now), I did the following. I don't know if it's required to do all this, but I did get it to work on two systems that both were erroring during plugin installation.

1. my android studio (sdk) ended up looking like this. I uninstalled android studio and reinstalled it, then went to tools, "checked" Android SDK Build-Tools 28RC2 and hit apply
![assdktools](https://user-images.githubusercontent.com/7697076/40552019-6f0bc1fe-5ff3-11e8-853f-8029e0243a99.png)
![assdk](https://user-images.githubusercontent.com/7697076/40552020-6f389b70-5ff3-11e8-979b-92c377cfb2f5.png)


2. install the plugin `cordova plugin add cordova-plugin-local-notification`
3. remove node_modules `rm -rf node_modules`
4. clear node cache `npm cache clean -f`
5. reinstall node_modules `npm install`
6. remove android platform `cordova platform rm android`
7. remove iOS platform `cordova platform rm ios`
8. update cordova `npm i cordova@7.1.0 -g`
9. add platforms back in `cordova platform add android; cordova platform add ios`

in step 9 above, watch for errors while the plugins are being installed—cordova-plugin-local-notification should install without error

**Comment by Tawpie** [comment] 2018-05-25 15:20
oh. I forgot to mention the critical step 10.

10. Cross your fingers, find your lucky charm and hold it close to your left ear then turn around clockwise three times. With your eyes still closed, reverently face your computer and chant (softly): "oh mighty machine". Bowing down to the computer is optional. Then run `cordova build android`

**Comment by Gamerakki** [comment] 2018-05-28 07:58
Hi @Tawpie  @katzer  @rwillett I tried the above step but still getting that error. Can u please help in this i am stuck in a project its a needed feature . Please help

**Comment by Tawpie** [comment] 2018-05-28 16:41
@Gamerakki as I mentioned, your issue is different than mine—your listing is pointing to the `import` statement. `import` as you are aware, is a newer JS construct not available in ES5/2015 and your node installation appears (I don't know for sure) to be unable to find the `import` statement. I'd suggest a couple of things:

1. make sure you have a raft of babel npm packages installed (there are a lot of them, `npm ls | grep babel`), these transpile ES6 to ES5. These are the base packages I have installed.
    "babel-polyfill": "~6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": ">=6.24.0", (not really necessary, babel-preset-env supersedes this)
    "babel-preset-stage-3": "^6.24.1", (not really necessary, babel-preset-env supersedes this)
    "babel-cli": "^6.14.0",
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
2. if you do have babel properly installed or if you need help figuring out which are the essential packages, ask a question in the node.js community—they'll be better able to help find the cause of a missing `import` class

I kind of doubt your issue has its root cause in this plugin… it might be (ionic has a history of being slightly problematic), but until you can get past the import statement it's difficult for folks supporting this plugin to help.

**Comment by Gamerakki** [comment] 2018-05-29 08:26
Hi @Tawpie ,
i went to the error deeply and found that one on the class in android import is not present for the latest local notification plugin. The media style import is failing in the code so i believe its the issue with the plugin and not of npm.

**Comment by Tawpie** [comment] 2018-05-29 13:55
kk. I'm not sure I can help anymore. I got 0.9.0-beta.3 to work for me so I'd just make sure you don't have a bad download of beta.**3**.

**Comment by Gamerakki** [comment] 2018-05-29 14:09
hi @Tawpie   can u share the beta plugin 3 on my email id fatalerror.android@gmail.comc would be helpful

**Comment by Tawpie** [comment] 2018-05-29 14:13
you should be able to get beta.3 by cloning or downloading this repo (I would also add the fix discussed in issue 1541 as well) and then installing from your local copy.

**Comment by Gamerakki** [comment] 2018-05-29 14:14
Thank you can i know when would u merge the fix with the repo so that i can download any headsup ?

**Comment by Tawpie** [comment] 2018-05-29 14:18
There is a pull request to fix 1541 already but due to what looks like an issue with CI it's not passing testing. Check that issue for details. I'm not the maintainer of this plugin (just a long time user) so I can't speak to when or if anything gets merged.

**Comment by josuper** [comment] 2019-03-09 16:03
Still getting bug, help @Tawpie 


Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 3.9.2
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 3.2.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v8.15.1
Xcode version: Not installed


------

 npm -v
6.8.0

**Comment by josuper** [comment] 2019-03-18 18:19
someone solved ? how ?

 cordova -v
6.4.0

npm -v
6.9.0

**Comment by Tawpie** [comment] 2019-03-18 23:50
@josuper this is a pretty old issue and you should be able to build android—I would recommend you make certain you're using the latest version of the plugin. I believe a number of PRs were merged recently, make sure you're on that version!

**Comment by luoenzhen** [comment] 2019-04-02 04:04
I upgrade the gradle and gulp to solve the issue.
- npm install gradle@3.5.0
- npm install gulp-useref@2.1.0

**Comment by Andrius0124** [comment] 2019-12-19 10:28
Still an issue for me 
cordova -v 9.0.0 (cordova-lib@9.0.1)
npm -v 6.10.0

**Comment by mnwer595** [comment] 2020-05-24 22:29
l faced the same error !!! any help

**Comment by sts-ryan-holton** [comment] 2020-08-27 08:49
Same issue, what's the workaround or fix

**Comment by naqeeb-klabs** [comment] 2021-02-23 11:18
Same issue, any one here found any solution for this?

**Comment by tony123S** [comment] 2021-03-05 14:48
Please fix !

**Closed** 2024-09-26 20:35 UTC
