### ISSUE TITLE
“doesn't support this project's cordova-android version”

### ISSUE THREAD

**Issue by QNDeveloper** [katzer/cordova-plugin-local-notifications#1597] opened 2018-05-06 19:46 UTC
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:
* Platform:android
* OS version:Windows 10
* Device manufacturer / model:
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```):android 7.0.0
* Plugin config
* Ionic Version (if using Ionic)
I have tried to install the plugin using git url for latest version  or older versions , same error
Plugin doesn't support this project's android-sdk version. android-sdk: 23.0.0, failed version requirement: >=26
Skipping 'cordova-plugin-local-notification' for android

Kindly note that I am using android-sdk 26 
So kindly let me know what is the procedure to follow and how to do it

**Comment by xudongcamsys** [comment] 2018-05-18 13:38
same issue here. except my android-sdk is 21. I have installed all updates through Android Studio. Not sure where to make the change to meet this plugin's requirements.

**Comment by dpa99c** [comment] 2019-05-23 17:34
Duplicate of #1561

**Closed** 2024-09-26 20:35 UTC
