### ISSUE TITLE
How to unbind click event?

### ISSUE THREAD

**Issue by lechenging** [katzer/cordova-plugin-local-notifications#1300] opened 2017-05-26 03:53 UTC
**WARNING: If you ignore this template, we'll ignore your issue.**

Provide a general summary of the issue.

## Your Environment

* Plugin version:1.0.0
* Platform:android 5.0 
* OS version: no
* Device manufacturer / model:
* Cordova version (```cordova -v```):6.5.0
* Cordova platform version (```cordova platform ls```):6.5.0
* Plugin config

## Expected Behavior
how to unbind click event, after bind

## Actual Behavior
```
document.addEventListener('deviceready', function () {
          cordova.plugins.notification.local.schedule({
            id: noticeId || 1,
            title: title || '消息通知',
            text: text,
            at: new Date().getTime(),
            //badge: 2,  应用图标的徽章
            autoClear: true, //默认值  
            sound: 'res://platform_default', //默认值  
            icon: 'res://ic_popup_reminder', //默认值  
            data: data || {},
            ongoing: true //默认值  false
          });
          cordova.plugins.notification.local.on('click', function (notification) {
              callback(notification.data);
            });
```

## Context

click event will be bind when receive notification every time. But, the click event will be fired many times also, after receive several notifications.

## Debug logs

no logs

```

**Comment by rwillett** [comment] 2017-05-26 05:08
I'm not sure what the problem is here. You need to explain it in a simpler way.

One issue that I can see is that you schedule the notification immediately, don't, you MUST schedule it in the future by a few seconds.

**Comment by rwillett** [comment] 2017-05-30 20:22
No update from OP in five days after requested so closing.

**Closed by rwillett** 2017-05-30 20:22 UTC

**Comment by katzer** [comment] 2017-05-31 06:36
@lechenging You can unbind an even with `un`:

```js
cordova.plugins.notification.local.on('click', callback);
...
cordova.plugins.notification.local.un('click', callback);
```

To unbind an even callback you have to pass the same function you have bound before!
