### ISSUE TITLE
what happened to the id property

### ISSUE THREAD

**Issue by akreienbring** [katzer/cordova-plugin-local-notifications#479] opened 2015-03-24 18:43 UTC
Hello, I just updated to version 0.8.1 of your (fabulous) plugin.
In an earlier version i could set the id property to an arbitrary string like this: 
```
				plugin.notification.local.add({
					id: "someString",
				});
```
and check for that string in the onClick event.
Now, in version 0.8.1 i basically do the same:
```
				cordova.plugins.notification.local.schedule({
					id: "someString",
				});
```
but when checking for the id with
```
cordova.plugins.notification.local.on("click", function (notification, state) { ...
```
notification.id is always just 0

Is this a bug or is the id supposed to be numeric now?

**Comment by katzer** [comment] 2015-03-24 18:54
@akreienbring, the id was always supposed to be numeric.

**Comment by akreienbring** [comment] 2015-03-24 19:10
Sad! A string is much more intuitive if check for it like i do it with:
```
		cordova.plugins.notification.local.on("click", function (notification, state) {
				switch (notification.id) {
				case 1: //"EnterRegion":

**Comment by akreienbring** [comment] 2015-03-24 19:18
I just figured out that the notification.id is still of type 'string'. So I'll have to use:
```
        cordova.plugins.notification.local.on("click", function (notification, state) {
                switch (notification.id) {
                case "1":
```

**Comment by katzer** [comment] 2015-03-25 16:53
OK, notification.id should return a number. Internally a number is required because OS APIs requires a number

**Comment by akreienbring** [comment] 2015-03-25 17:17
Does that mean that you are going to change typeof notification.id to be numeric in future versions?

**Comment by katzer** [comment] 2015-03-25 19:42
@akreienbring, yes that bug will be fixed to be numeric - sorry for that

**Comment by atuttle** [comment] 2015-03-31 18:08
I'm currently debugging an issue that I think this may be the root cause. Here's some sample XCode debug output:

> 2015-03-31 14:03:38.255 Reunion[303:33158] WARN: Unknown property: autoClear
2015-03-31 14:03:38.257 Reunion[303:33172] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x1763d900
2015-03-31 14:03:38.259 Reunion[303:33172] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x1763d900'
*** First throw call stack:
(0x2aa8a5a7 0x38670c77 0x2aa8fa6d 0x2aa8d949 0x2a9beb68 0x606d1 0x60287 0x627c7 0x62621 0x5bc5b 0x32e19b 0x338c49 0x339e21 0x38d5cda9 0x38d5cafc)
libc++abi.dylib: terminating with uncaught exception of type NSException

I'll try switching to a numeric ID value in my call to `.schedule()` to see if that addresses it.

**Comment by atuttle** [comment] 2015-03-31 18:25
Unfortunately switching to a numeric ID doesn't seem to have resolved my error. I should also note that before I switched to the new `.schedule()` api and was still using the `.add()` api, my notification had no issue displaying, even with an alphanumeric ID.

---

I was able to get it working, however. Here's the code I'm using to create the notification:

	window.plugin.notification.local.schedule({
		id: that.notificationCount //numeric
		,title: that.knownBeacons[ id ].notificationTitle //string
		,text: that.knownBeacons[ id ].notificationBody //string
		,data: JSON.stringify({ id: id })
	});

So, you say that passing an object should work for the `data` attribute, but at least in my experience, that is not the case. I also opted to omit the `every` attribute because I was just using the default value anyway.

**Comment by salvadorhol** [comment] 2015-04-02 17:56
@atuttle my iOS app is still crashing and I'm getting a similar error to yours on xcode: 
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb000000000000003'
```
This issue force closes the app as soon as the notification is scheduled. I have tried different versions of the plugin along with your suggestion to get it working but still no luck.

**Comment by jabjab** [comment] 2015-04-09 22:08
@atuttle That doesn't make a difference, the javascript interface converts all IDs to strings anyway. It seems the issue is that, despite all the effort to store the IDs as strings, somehow the numeric value sneaks in. What's odd about this is that UILocalNotification doesn't have such an ID property to utilize, it's stored as an entry in the userInfo dict, which is none other than the options object you pass into `schedule` and the like; the ID is only used within the plugin to keep track of which notification it creates is which, and does not appear to be accessed by anything other than those. @salvadorhol I think the issue may be caused by some form of data corruption when you create an invalid notification, as I've been trying to test and reproduce the bug but it isn't occurring anymore for me.

**Closed** 2015-05-02 09:23 UTC
