### ISSUE TITLE
Notifications are not appearing after a device restart

### ISSUE THREAD

**Issue by stas4000** [katzer/cordova-plugin-local-notifications#1495] opened 2018-01-06 20:32 UTC
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.9-beta
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: LG V20
* Cordova version (```cordova -v```):  7.1.0
* Cordova platform version (```cordova platform ls```): 6.3.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Notification should show every one minute

## Actual Behavior

After restart of device, notifications don't appear anymore

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

   document.addEventListener("deviceready", function() {
        cordova.plugins.notification.local.schedule({
            title: 'My notification',
            text: 'some text',
            trigger: {every: 'minute', count: 20}
        });
    });

## Context

To show a notification once a minute for 20 times (for testing purposes)

## Debug logs

_Include iOS / Android logs_

This is the Logcat:
[logcat.txt](https://github.com/katzer/cordova-plugin-local-notifications/files/1609198/logcat.txt)

**Comment by katzer** [comment] 2018-01-09 12:40
I close this because its duplicated and I am aware of it ;)

**Closed by katzer** 2018-01-09 12:40 UTC
Labels: android, duplicate

**Comment by voidbrain** [comment] 2018-03-09 14:51
it's a duplicated of which one? any solution?

**Comment by marcovtwout** [comment] 2018-10-23 07:41
Duplicate of https://github.com/katzer/cordova-plugin-local-notifications/issues/1449
