### ISSUE TITLE
isPresent() returns true after user clear notification, on iOS

### ISSUE THREAD

**Issue by tamy83** [katzer/cordova-plugin-local-notifications#936] opened 2016-04-14 21:25 UTC
On iOS, after the user clears the notification from the notifications list, isPresent(id, function(present){}) is still returning present = true in the callback. Only after you specifically call cancel() will isPresent() return  false.

Tested on cordova 4.3, iOS 8.4, not sure if it happens on iOS 9.

**Comment by tamy83** [comment] 2016-04-15 14:42
After looking into this more, its not really a bug but more a quirk of iOS where clearing it from the notification center doesn't remove the notification object.

**Comment by rwillett** [comment] 2017-03-05 07:32
Closed as not a bug or issue, just 'a quirk of iOS'.

**Closed by rwillett** 2017-03-05 07:32 UTC
