### ISSUE TITLE
Notification not settled

### ISSUE THREAD

**Issue by iskydive** [katzer/cordova-plugin-local-notifications#1347] opened 2017-07-16 18:36 UTC
Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.5
* Platform: android
* OS version: 7.1.1
* Device manufacturer / model: OnePlus 5
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):
```
Installed platforms:
  android 6.2.3
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0
```
* Plugin config : ??
* Ionic Version (if using Ionic) : 2

## Expected Behavior

To set a local notification

## Actual Behavior

No notification is added

## Steps to Reproduce

I don't really know, I think that i'm not doing something good but I don't really know what ...

I installed the plugin, added it to the imports in app.module.ts, added it in the providers.

Here is my notif-modal.ts code which is called on button click :

```
...
import { LocalNotifications } from '@ionic-native/local-notifications';

export class NotifModalPage {

  constructor(public navCtrl: NavController, public navParams: NavParams, public viewCtrl: ViewController, public storage: Storage, public platform: Platform, public localNotifications: LocalNotifications, private calendar: Calendar, private datePicker: DatePicker) {  

    }

  closeModal() {
    let firstNotificationTime = new Date();
    firstNotificationTime.setMinutes(firstNotificationTime.getMinutes() + 1);
    this.localNotifications.schedule({
        id: 1,
        title: 'Hey!',
        text: 'You just got notified :)',
        at: firstNotificationTime
    });
    
    this.viewCtrl.dismiss();
  }
}
```

## Context

I wanted to set a simple notification, to try out the plugin and be able to use it therefor, and it didn't worked so i'm here to ask some help

**Comment by Tawpie** [comment] 2017-07-17 00:16
Try quitting the app after you set the notification. iOS (I'm not certain about Android's default) won't show the notification when the app is foregrounded.

(spelling and grammer powered by autocorrupt)

**Comment by iskydive** [comment] 2017-07-17 09:10
Doesn't work neither, in fact, when I try to install the plugin as in the tutorial, at the end, I do not have the plugin in my plugins list ... ?

**Comment by iskydive** [comment] 2017-07-17 09:12
Doesn't work neither, I thought the same but that is not the problem ...

**Comment by Mantas-Skackauskas** [comment] 2017-07-21 10:19
Same problem here. Took me a while to successfully install cordova notification plugin. However, notifications still don't show up.

**Comment by haard** [comment] 2017-07-26 13:52
I have the same issue, on Android.

**Comment by sstorie** [comment] 2017-07-31 13:49
I don't have any meaningful answers to provide, but I keep experiencing flaky behavior when I build my Ionic app for android (especially with AOT). Sometimes the notifications work as intended, sometimes they don't. For example, the notification will fire, but not execute my event handlers, so the code I have to mark it as triggered gets ignored and notifications keep firing. What I keep seeing though is this console error when I debug the device using Chrome's inspector:

> (Warning) Native: tried calling LocalNotifications.on, but the LocalNotifications plugin is not installed.
> (Warning) Install the LocalNotifications plugin: 'ionic cordova plugin add de.appplant.cordova.plugin.local-notification'

I haven't been able to figure out what I'm doing to keep having to re-install the plugin, but there must be something I'm missing. 

Here's what I'm running:
- Cordova 6.2.3
- Android 7.1.2
- Google Pixel

**Comment by wbhob** [comment] 2017-08-09 04:53
I also have this issue. I wish @katzer could contribute to help resolve these issues, or find a new maintainer. This plugin is very widely used, yet riddled with bugs.

**Comment by katzer** [comment] 2017-10-31 10:52
Without Ionic it works fine :)

At the moment I cant tell much things about Ionic. Their current wrapper does not work with 0.9-beta. Because many are using the plugin+ionic I will contribute to the ionic-native wrapper in future.

But for now I am closing all ionic related tickets because they point to old code and/or Ionic.

**Closed by katzer** 2017-10-31 10:52 UTC
Labels: android, Ionic 2
