### ISSUE TITLE
Android 12 (SDK 31+): Tap on notifications only opens app when notifications are grouped.

### ISSUE THREAD

**Issue by fragfeaster777** [katzer/cordova-plugin-local-notifications#1990] opened 2022-10-19 18:16 UTC
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 
* cordova-plugin-local-notification-12 0.1.3 "LocalNotification"
* cordova-plugin-badge-fix 0.8.10 "Badge"
* Platform: Android
* OS version: 12
* Device manufacturer / model: n/a
* Cordova version (```cordova -v```): 11.0.0
* Cordova platform version (```cordova platform ls```):  android 10.1.1

## Expected Behavior

On Android 12, after an app is killed or in the background, tapping on a notification does not open the app. Adb logcat shows the following: 

NotificationService: Indirect notification activity start (trampoline) from com.xxx.xxx blocked

The same happens when 2 and 3 notifications from the same app have been queued up.

However, when more than 3 notifications are queued and these notifications are grouped together, tapping on any of these notifications opens up the app.

Happy to do any testing to further debug.

## Actual Behavior

App should open with tapping a single notification

## Steps to Reproduce

  1. When a single notification is triggered, tap on it. App is not opened.
  2. When 2 or 3 notifications are triggered, tapping on any of them doesn't open the app.
  3. When notifications are grouped, tapping on any of them opens up the app.

## Context

Open app when tapping notification

## Debug logs

NotificationService: Indirect notification activity start (trampoline) from com.xxx.xxx blocked

**Comment by fragfeaster777** [comment] 2022-10-19 18:20
Related:

https://github.com/wix/react-native-notifications/issues/884
https://github.com/katzer/cordova-plugin-local-notifications/issues/1989
https://github.com/katzer/cordova-plugin-local-notifications/issues/1970

**Comment by Filavision** [comment] 2022-10-20 16:33
I have the same issue...

**Comment by rafaellop** [comment] 2022-10-22 12:22
The issue and solution is described here:
https://proandroiddev.com/notification-trampoline-restrictions-android12-7d2a8b15bbe2

**Comment by rafaellop** [comment] 2022-10-22 12:34
@bhandaribhumin or @DavidTalevski could you look please at it?

**Comment by DavidTalevski** [comment] 2022-10-22 13:07
Can you try my [fork](https://github.com/DavidTalevski/cordova-plugin-local-notifications) and confirm if the issue persists there?

**Comment by Filavision** [comment] 2022-10-22 13:16
> Can you try my [fork](https://github.com/DavidTalevski/cordova-plugin-local-notifications) and confirm if the issue persists there?

The app still doesn't open when i click on the notification. I have also a refresh button at the notification which refresh a random number in the notification. This button also doesn't work anymore with your fork.

**Comment by DavidTalevski** [comment] 2022-10-22 13:18
> > Can you try my [fork](https://github.com/DavidTalevski/cordova-plugin-local-notifications) and confirm if the issue persists there?
> 
> The app still doesn't open when i click on the notification. I have also a refresh button at the notification which refresh a random number in the notification. This button also doesn't work anymore with your fork.

Are there any errors reported in logcat?

**Comment by Filavision** [comment] 2022-10-22 13:57
Tested again. The refresh button works (don't know what happens at the first test) but the app doesn't come in foreground / open when clicking on the notification.

Logcat:
```
10-22 15:48:01.240  1285  4684 D ActivityTaskManager: startActivityAsUser: callingPid=1428, callingUid=10399, caller=com.android.server.wm.ActivityTaskManagerService.startActivityAsUser:1739 com.android.server.wm.ActivityTaskManagerService.startActivity:1692 android.app.IActivityTaskManager$Stub.onTransact:1132 com.android.server.wm.ActivityTaskManagerService.onTransact:6218 android.os.Binder.execTransactInternal:1215 android.os.Binder.execTransact:1179 <bottom of call stack> 
10-22 15:48:01.243  1285  4684 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30020000 pkg=com.myapp.app cmp=com.myapp.app/.MainActivity} from uid 10399
10-22 15:48:01.243  1285  4684 E NotificationService: Indirect notification activity start (trampoline) from com.myapp.app blocked
10-22 15:48:01.244  1285  4684 W ActivityTaskManager: Background activity start [callingPackage: com.myapp.app; callingUid: 10399; appSwitchAllowed: true; isCallingUidForeground: false; callingUidHasAnyVisibleWindow: false; callingUidProcState: SERVICE; isCallingUidPersistentSystemProcess: false; realCallingUid: 10399; isRealCallingUidForeground: false; realCallingUidHasAnyVisibleWindow: false; realCallingUidProcState: SERVICE; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; allowBackgroundActivityStart: false; intent: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30020000 pkg=com.myapp.app cmp=com.myapp.app/.MainActivity }; callerApp: ProcessRecord{524e055 1428:com.myapp.app/u0a399}; inVisibleTask: false]
10-22 15:48:01.244  1285  4684 D ActivityTaskManager: TaskLaunchParamsModifier:task=null activity=ActivityRecord{7c5b2f5 u0 com.myapp.app/.MainActivity display-from-launchedFrom=0 display-id=0 display-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@21040948
10-22 15:48:01.244  1285  4684 D ActivityTaskManager: TaskLaunchParamsModifier:task=Task{8baa509 #12911 type=standard A=10399:com.myapp.app U=0 visible=false mode=fullscreen translucent=true sz=1} activity=ActivityRecord{7c5b2f5 u0 com.myapp.app/.MainActivity t-1} display-from-task=0 display-id=0 display-windowing-mode=1 suggested-display-area=DefaultTaskDisplayArea@21040948 non-freeform-display display-area=DefaultTaskDisplayArea@21040948 maximized-bounds
```

**Comment by rafaellop** [comment] 2022-10-22 14:06
@DavidTalevski I use your fork because it's most recent and the issue occurs in your fork as well. The log cat error is `Indirect notification activity start (trampoline) from com.myapp.app blocked` and the issue is described with a solution in the link given above. I checked the builder.java sources but I'm not feel enough good to modify that and I noticed there's no reference to the `NotificationTrampolineActivity` which is the source of the problems as described in the link.

**Comment by DavidTalevski** [comment] 2022-10-22 14:38
Currently I don't have an android 12 phone available, nor can I simulate one, in order to reproduce the issue and implement the fix. I might be able to get my hands on one next week. If someone implements the fix I will be more than happy to include it in my fork.

**Comment by bhandaribhumin** [comment] 2022-10-22 19:56
@rafaellop please use my fork version https://github.com/bhandaribhumin/cordova-plugin-local-notification-12, this version includes all latest fixes and also compatible with sdk 30,31,32 and 33 as well.
Please let me know if you found any issues.

**Comment by rafaellop** [comment] 2022-10-23 06:50
@bhandaribhumin I'll try but from what I have see in the repo your fork also doesn't refer the trampoline so I don't expect it works, but I'll try just to confirm that.

**Comment by rafaellop** [comment] 2022-10-24 07:40
> Currently I don't have an android 12 phone available, nor can I simulate one, in order to reproduce the issue and implement the fix. I might be able to get my hands on one next week.

Please take a look when you have the v12 phone. Thank you.

**Comment by Filavision** [comment] 2022-10-24 09:53
I realized that when I closed the app with the back button `navigator.app.exitApp();`, clicking on the notification opens the app. If I just push the app to the background or close the app completely, clicking the notification doesn't work.

**Comment by bevinGithub** [comment] 2022-10-24 19:56
> @rafaellop please use my fork version https://github.com/bhandaribhumin/cordova-plugin-local-notification-12, this version includes all latest fixes and also compatible with sdk 30,31,32 and 33 as well. Please let me know if you found any issues.
> 
> Also use this method to request permission https://github.com/bhandaribhumin/cordova-plugin-local-notification-12#setdummynotification
> 
> This plugin also available on npm https://www.npmjs.com/package/cordova-plugin-local-notification-12

Hi Rafellop
Does your fix also include the triggering of events e.g onTrigger also last  local notifcation for android 12 did not have events or were not functional.

**Comment by rafaellop** [comment] 2022-10-31 07:29
> Currently I don't have an android 12 phone available, nor can I simulate one, in order to reproduce the issue and implement the fix. I might be able to get my hands on one next week. If someone implements the fix I will be more than happy to include it in my fork.

@DavidTalevski have you maybe managed to put your hands on an Android 12 device to verify that?

**Comment by bevinGithub** [comment] 2022-11-01 11:23
> > Currently I don't have an android 12 phone available, nor can I simulate one, in order to reproduce the issue and implement the fix. I might be able to get my hands on one next week. If someone implements the fix I will be more than happy to include it in my fork.
> 
> @DavidTalevski have you maybe managed to put your hands on an Android 12 device to verify that?

Hi Rafaellop.

I am using local notifications and the local notifications 12 is not supporting the events subscription, are you able to resolve this on your fork also? I need the event onTrigger on the local notifications. The code below works on lower version of the plugin are you able to set this up on your fork.

onDeviceReady() {
this.localNotifications.on('trigger').subscribe((test: any) => {
console.log('Trigger' + JSON.stringify(test));
});
}

**Comment by bevinGithub** [comment] 2022-11-01 11:25
> @rafaellop please use my fork version https://github.com/bhandaribhumin/cordova-plugin-local-notification-12, this version includes all latest fixes and also compatible with sdk 30,31,32 and 33 as well. Please let me know if you found any issues.
> 
> Also use this method to request permission https://github.com/bhandaribhumin/cordova-plugin-local-notification-12#setdummynotification
> 
> This plugin also available on npm https://www.npmjs.com/package/cordova-plugin-local-notification-12
Hi Bhandaribhumin

Are you able to  subscribe to events on your fork version?. I'm using this plugin and the android 12 is not subscribing to events onTrigger. Your assistance will be much appreciated.

**Comment by rafaellop** [comment] 2022-11-01 13:04
No event works properly.

**Comment by bevinGithub** [comment] 2022-11-01 13:31
I have installed this fork link  https://github.com/bhandaribhumin/cordova-plugin-local-notification-12 last week, l can assure you the events function call below does not register when the Local notification is triggered. Please sent me the right fork link of the local notifications l can reinstall a new one.

onDeviceReady() {
this.localNotifications.on('trigger').subscribe((test: any) => {
console.log('Trigger' + JSON.stringify(test));
});
}

**Comment by bevinGithub** [comment] 2022-11-01 14:16
My apologies of the misinterpretation of your comment, the events is this something in progress or there is no hope on the plugin?

**Comment by bevinGithub** [comment] 2022-11-01 20:30
Hi Powowbox.

Does your fix also include other events e.g ontrigger  code below.
onDeviceReady() {
this.localNotifications.on('trigger').subscribe((test: any) => {
console.log('Trigger' + JSON.stringify(test));
});
}

**Comment by powowbox** [comment] 2022-11-01 21:27
Hi bevinGithub,
I made at test by running 

`cordova.plugins.notification.local.schedule({id: 3, text: "xxxx", triggerInApp: true, trigger: {at: new Date(new Date().getTime() + 5000)}})`

the trigger event is correctly raised.

**Comment by bevinGithub** [comment] 2022-11-02 05:45
Hi Powowbox.

I am using ionic l will try install your version and test it thanks very much for the response.

**Comment by powowbox** [comment] 2022-11-02 07:20
Sorry, I can’t help I don’t use awesome-cordova-plugins.

**Comment by bevinGithub** [comment] 2022-11-02 07:28
Im just showing you how l import awesome-cordova-plugins. I want to know how to import your cordova plugin in ionic.

**Comment by powowbox** [comment] 2022-11-02 09:42
use `cordova plugin add https://github.com/powowbox/cordova-plugin-local-notification-12.git --save --noregistery`. Then check in your package.json, you must find a line like ` "cordova-plugin-local-notification-12": "git+https://github.com/powowbox/cordova-plugin-local-notification-12.git",` in the dependencies object and in the plugins object you must find ` "cordova-plugin-local-notification-12": {}`.

**Comment by bevinGithub** [comment] 2022-11-02 12:05
I have already installed the plugin its in the package Json. I am asking how do you import the plugin for use in pages. 
or app-modules.ts

**Comment by bevinGithub** [comment] 2022-11-03 05:53
hi Powowbox.

The setting triggerInapp does make the plugin subscribe to events but stops the notification being displayed in the phones default notifications area even if the foreground setting is true. Is there  way to show the notification popup if the app is closed as the phone just vibrates and the light is on and plays the sound and no popup of notification these are the settings l have
    cordova.plugins.notification.local.schedule({
      id: 3,
      text: 'xxxx',
      foreground: true,
      lockscreen: true,
      priority: true,
      triggerInApp: true,
      data: { name: 'Bevin', surname: 'Masevenza', cell: '0734913786' },
      trigger: {at: new Date(new Date().getTime() + 5000)}
    });

**Comment by powowbox** [comment] 2022-11-03 09:40
@bhandaribhumin Hi, thanks for merging my changes. I haven't done any test on your merge, I only look at the merge. It sounds good.

**Comment by powowbox** [comment] 2022-11-03 10:33
Hi, @bevinGithub 
`// Show notification if we should (triggerInApp is false)
        // or if we can't trigger in the app due to:
        //   1.  No autoLaunch configured/supported and app is not running.
        //   2.  Any SDK >= Oreo is asleep (must be triggered here)
        boolean didShowNotification = false;
        if (!options.triggerInApp() ||
            (!autoLaunch && !checkAppRunning())
        ) {
            didShowNotification = true;
            notification.show();
        }
`

Following the code above, it seems the behaviour you describe corresponds to the expected one. 
If you enable the trigger option, when the app is visible, it's its responsability to display the notification to the user, so no need to display it in the notification center.
If the app is closed, since the app cannot display the notification, it must be displayed in the notification center.

There is one last case, that sounds to not be correctly handled: when the app is in background, the notification isn't displayed in the notification center even if the app cannot displayed show it to the user.  I can try to fix it.

**Comment by powowbox** [comment] 2022-11-03 11:08
If I understand well, if triggerInApp is set to true, you want to display the notification in any case,  the app is visible or not. It's a very specific need. You can make your own fork. To have the expected behaviour, in the file AbstractNotificationReceiver, change the condition in 

`
        if (!options.triggerInApp() ||

            (!autoLaunch && !checkAppRunning())

        ) {

            didShowNotification = true;

            notification.show();

        }
`


Remove  !options.triggerInApp() from the test and you should have what you want.

**Comment by bevinGithub** [comment] 2022-11-03 11:41
Hi Powowbox.

If l remove the triggerInApp: Yes l am not able to subscribe to event onTrigger, the below code will not work if triggerInApp is false or is removed completely.

onDeviceReady() {
this.localNotifications.on('trigger').subscribe((test: any) => {
console.log('Trigger' + JSON.stringify(test));
});
}

**Comment by bhandaribhumin** [comment] 2022-11-03 14:01
Hello @bevinGithub  you can use this [method](https://github.com/bhandaribhumin/cordova-plugin-local-notification-12/tree/Android12-NotificationTrampoline-Fix#setdummynotification) to prompt for runtime permission.

**Comment by bevinGithub** [comment] 2022-11-03 18:36
Hi Bhandaribhumin.

I am looking to just get  trigger events after the notification triggers l subscribe to the event onTrigger to play custom audios or sound.
onDeviceReady() {
this.localNotifications.on('trigger').subscribe((test: any) => {
console.log('Trigger' + JSON.stringify(test));
});
}

if i have the code below, triggerInApp: true does make evet subscrition happen if  l set it to false the trigger events don't work
I need trigger events to work at the same time the notification gets displayed in the notifications center. 
cordova.plugins.notification.local.schedule({
id: 3,
text: 'xxxx',
foreground: true,
lockscreen: true,
priority: true,
triggerInApp: true,
data: { name: 'Bevin', surname: 'Masevenza', cell: '0734913786' },
trigger: {at: new Date(new Date().getTime() + 5000)}
});

**Comment by Filavision** [comment] 2022-11-07 04:41
> Hi @powowbox Thanks for the fix, I've added your fix to my [branch](https://github.com/bhandaribhumin/cordova-plugin-local-notification-12/tree/Android12-NotificationTrampoline-Fix). Can you please take a look if everything looks goot to you then I'll merge to main. Thanks a lot, cheers.

Hey! Click on the notification doesn't open my App. I have a "refresh" button in my notification to refresh a number in the notification. Clicking the refresh button open the app but clicking the notification does nothing. The app should open when clicking the notification and should not open when clicking the refresh button.

**Comment by powowbox** [comment] 2022-11-07 07:39
@Filavision Hi.
On my fork, If an action is set, the click on the notification is disabled to avoid the user clicks involuntary on the notification before discovering the action button.
I see 2 options: you add another button ‘open app’ or I restore the previous behavior and add an option ‘disableNotificationClick’.

**Comment by fquirin** [comment] 2022-11-16 19:20
Some info to actually explain why "tap on notifications" does not open the app in Android 12. It is because of [Notification trampoline restrictions](https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines). If you deactivate the flag `NOTIFICATION_TRAMPOLINE_BLOCK` for your app in Android developer options (e.g. on Emulator) it will work again ... obviously this is not a solution, just a test.
The issue seems to be that the `PendingIntent` attached to the click (the plugin has a `ClickReceiver` class) is a service not an activity and thus is not allowed to trigger `context.startActivity()` anymore. I'm currently banging my head against a wall to find how why Google would mess up the API like this 🤕.

@powowbox I see you've refactored `AbstractClickReceiver` to use an activity instead of a service. That was exactly what I was planning to try next 👍 . Will check it out to see what else you've changed 🙂 .

**Comment by powowbox** [comment] 2022-11-16 20:12
@fquirin  
Hi, my fork is fully functional  on android 12 and 13. Just be careful, if you use action buttons in your notifications. In this case, I voluntarily disable the click on the  notification to avoid the user clicks on notification before discovering the buttons.

**Comment by fquirin** [comment] 2022-11-16 20:14
> Hi, my fork is fully functional on android 12 and 13. Just be careful, if you use action buttons in your notifications. In this case, I voluntarily disable the click on the notification to avoid the user clicks on notification before discovering the buttons.

Saw that and I think it makes total sense 👍 . Any other breaking changes?
Code looks good so far, I'll probably replace [my own fork](https://github.com/fquirin/cordova-plugin-local-notifications) with your one 🙂

**Comment by powowbox** [comment] 2022-11-16 20:32
@fquirin 
For the change list, look at the section "Purpose of this fork" on the page of the fork.
I've done several tests since the last two week on android 7, 12 and 13 and I didn't notice any problem.

**Comment by fquirin** [comment] 2022-11-20 17:36
I've merged all changes from [@timkellypa](https://github.com/timkellypa/cordova-plugin-local-notifications), [@bhandaribhumin](https://github.com/bhandaribhumin/cordova-plugin-local-notification-12) and [@powowbox](https://github.com/powowbox/cordova-plugin-local-notification-12) into [my own fork](https://github.com/fquirin/cordova-plugin-local-notifications), so we could create a PR for the original repository. But since there are so many changes now, I doubt this PR would ever be accepted 😅

**Comment by bevinGithub** [comment] 2022-12-16 19:10
Hi guys are you able to do a fix on IOS for local notifications? events triggering when app is in the background is not subscribing to events IOS 16

**Comment by fquirin** [comment] 2022-12-27 12:41
@bevinGithub I'm not familiar with the iOS code, sorry.

**Comment by alitalaee** [comment] 2023-07-23 17:53
> Hi powowbox.
> 
> I have managed to to get your fork working now, the issue was to get the var reference of the cordova in ionic and call the function as you supplied before, thanks for your assistance the notifications events are working now.

How did you do that please?

**Comment by thiagoroc** [comment] 2023-09-20 21:03
> Hi, I've done a fix to make notifications clickable on android 12+. You can find it here https://github.com/powowbox/cordova-plugin-local-notification-12. If it's ok I will make a PR. Important: add `<preference name="AndroidLaunchMode" value="singleInstance"/>` in your config.xml, to avoid to launch the app even if it's in background.

This is solution for my problem. Thanks!

**Closed** 2024-09-26 20:32 UTC
