### ISSUE TITLE
Unable to cancel or clear the current notification

### ISSUE THREAD

**Issue by kjt1212** [katzer/cordova-plugin-local-notifications#860] opened 2016-02-02 07:46 UTC
I am scheduling several notifications in my app. However, when a certain notification is clicked I do not want to launch the app, I just want to clear the notification. I tried firing `cordova.plugins.notification.local.clear(notification.id, function() {});` and 
`cordova.plugins.notification.local.cancel(notification.id, function() {});`
However, they do not clear / cancel the current notification. Is there a way to do this?

**Comment by cess2014** [comment] 2016-03-28 22:50
I have the same error in my implementation, I need cancel or clear notification, but these methods not working,  I need your help to resolve problems.
Steps to reproduce:
1. Use schedule method and send a new notification
2. Use "cancel" or "clear" method
3. Restart your phone

Current result: It showing canceled or cleaned notification
Expected behavior: Not show a notification canceled or cleaned.

@katzer please help me to resolve this bug.

**Comment by oemilio16** [comment] 2016-03-30 02:19
I have the same problem.

i have many notifications in the app and i only want cancel one. This one notification was triggered but have a repeating interval, and not canceled the future notifications.

@katzer @cess2014 @kjt1212 Anyone have solution to this issue?

**Comment by oemilio16** [comment] 2016-03-30 23:03
Hello, I solved my problem by canceling notifications more than once if they stayed between pending notifications .

When the user activates the notification , it sends a message every 10 minutes, the problem was when he canceled after he had spent several notifications..

something like that:
` 
var schedule_time = new Date();
var hour= schedule_time.getHours();
var minutes= schedule_time.getMinutes();

schedule_time.setHours(hour,minutes+10,00);
schedule(20, "title", "message",schedule_time,"hour");

schedule_time.setHours(hour,minutes+20,00);
schedule(21, "title", "message",schedule_time,"hour");

schedule_time.setHours(hour,minutes+30,00);
schedule(22, "title", "message",schedule_time,"hour");

schedule_time.setHours(hour,minutes+40,00);
schedule(23, "title", "message",schedule_time,"hour");

schedule_time.setHours(hour,minutes+50,00);
schedule(24, "title", "message",schedule_time,"hour");

schedule_time.setHours(hour,minutes+60,00);
schedule(25, "title", "message",schedule_time,"hour");

 function schedule(id, titulo, mensaje, schedule_time,every)
  {
    cordova.plugins.notification.local.schedule({
        id: id,
        title: titulo,
        message: mensaje,
        firstAt: schedule_time,
        sound:"file://beep.caf",
        badge: true,
        every:every
    });
  }

cancelar(20);
cancelar(21);
cancelar(22);
cancelar(23);
cancelar(24);
cancelar(25);

  function cancelar(id){
    var id=id;
    cordova.plugins.notification.local.cancel(id, function() {
    });
  }
 cordova.plugins.notification.local.on('cancel', function (notification) {
            var id=notification.id;
            cordova.plugins.notification.local.isPresent(id, function (present) {
              if(present){
                cancelar(id);
              } 
            });

        });  `

PS: Works on iOs , I have not tried it on another operating system.

@kjt1212  @cess2014

**Comment by kjt1212** [comment] 2016-05-02 09:41
@oemilio16 thanks!

**Comment by rwillett** [comment] 2017-02-20 08:12
Is this still an issue otherwise I'll close it?

**Closed** 2017-02-25 19:24 UTC
Labels: Awaiting Information
