### ISSUE TITLE
iOS 11 plugin 0.8.4 AND 0.9.0-beta.2 not working 

### ISSUE THREAD

**Issue by voidbrain** [katzer/cordova-plugin-local-notifications#1537] opened 2018-02-14 14:59 UTC
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

Notifications are never triggered and permission request also not showed, brand new app.
cordova.plugins. 

cordova.plugins.notification.local.schedule({
    title: 'Design team meeting',
    text: '3:00 - 4:00 PM',
    trigger: { at: (new Date()).getTime() },
	foreground: true
});

After this code cordova.plugins.notification.local.getAll(function(nots){console.log(nots)}) gives me 
the correct list but no notification is triggered
Array (1)
0 Object
actions: [] (0)
attachments: [] (0)
autoClear: true
defaults: 0
foreground: false
groupSummary: false
id: 1
launch: true
led: true
lockscreen: true
meta: {version: "0.9-beta.2", plugin: "cordova-plugin-local-notification"}
number: 0
priority: 0
progressBar: {enabled: false, value: 0}
showWhen: true
silent: false
smallIcon: "res://icon"
sound: true
text: "3:00 - 4:00 PM"
title: "Uno"
trigger: {at: 1521033900000, type: "calendar"}
vibrate: false
wakeup: true

 
## Your Environment

* Plugin version: 0.8.4 AND 0.9.0-beta.2
* Platform: iOS
* OS version: 11.2.5
* Device manufacturer / model: Apple iPhone 8
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): osx ~4.0.1
* Plugin config 
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-whitelist 1.3.3 "Whitelist"
* Ionic Version (if using Ionic)
No
## Expected Behavior
notifications triggered
_Tell us what should happen_
notifications should be triggered
## Actual Behavior
nothing happens
_Tell us what happens instead_
nothing
## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  cordova.plugins.notification.local.schedule({
    title: 'Design team meeting',
    text: '3:00 - 4:00 PM',
    trigger: { at: (new Date()).getTime() },
	foreground: true
});

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by rwillett** [comment] 2018-02-14 16:29
1. Set your time to schedule a few seconds in the future.

2. Use the code formatting functions as it makes the code easier to read as well :) 

3. Normally worh putting an ```id:``` field in

4. Pluigin V0.8.4 doesn't work properly with IOS 11. Don't use it.

**Comment by voidbrain** [comment] 2018-02-14 16:40
thank you for you reply (and sorry for p.2)

I used new Date()).getTime() just for the example, in the real situation i have an array of notifications, all in the future (almost one at day). 

Really do I should avoid using ids??. 0.9.0-beta.2 still nothing happens

**Comment by Tawpie** [comment] 2018-02-14 17:53
@voidbrain Try making your trigger a date object (don't call .getTime() on new Date()), when you call .getTime() it returns a number object.

**Comment by GitToTheHub** [comment] 2018-02-15 14:02
Are you trying to schedule more than 64 Notifications? Could be possible a duplicate of #1535

**Comment by voidbrain** [comment] 2018-02-15 14:24
`cordova.plugins.notification.local.cancelAll(function(){
	for(i=1;i<4;i++){

		cordova.plugins.notification.local.schedule({    
            id:i,

		    title: 'notifica '+i,

 		    text: 'suvvia',

		    trigger: { at: new Date(2018, 1, 15, 15, 17+i) },

			foreground: true

		});

	}})

`
with 0.9-beta.2 works. Thank you

**Closed** 2018-02-15 14:26 UTC
Labels: Awaiting Information
