### ISSUE TITLE
Build failed for Android

### ISSUE THREAD

**Issue by Zapmobilegames** [katzer/cordova-plugin-local-notifications#832] opened 2016-01-14 10:40 UTC
I use Intel XDK and when passing to the new CLI 5.1.1 I got a build error and I can't use anymore your plugin. 

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
:compileArmv7ReleaseJava.../MyApp/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:130: error: cannot find symbol
                .setColor(options.getColor())
                ^
  symbol:   method setColor(int)
  location: class Builder
.../MyApp/platforms/android/src/de/appplant/cordova/plugin/notification/Options.java:262: error: cannot find symbol
            return NotificationCompat.COLOR_DEFAULT;
                                     ^
  symbol:   variable COLOR_DEFAULT
  location: class NotificationCompat
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileArmv7ReleaseJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Could you please fix it?

**Comment by bradrlaw** [comment] 2016-01-19 03:02
Running into the same issue with a different fork of the plugin.  The issue is the plugin is shipping with an android-support library that is causing conflicts with other plugins.

To solve it and get a build here are the steps I did:

1. Clean out any generated platform directory (platforms/android)
2. Comment out this line in the plugin's plugin.xml file:

3. Renamed the android-support-v4.jar file in the plugin's libs/android folder to use a .tmp directory (probably not needed, but just to make sure).

Was able to successfully build and everything works.

**Comment by HugoMcPhee** [comment] 2016-01-20 05:02
I fixed it by installing "Android Support Repository" in the Android SDK Manager

**Comment by spottuit** [comment] 2016-01-25 10:05
**Error**

I also had the same error. I inspected the *plugins folder and found some issues: 
- `src/android` was empty (other platforms too)
- `www` was empty
- There wasn't a `plugin.xml`.

There might have been more issues. 

**My solution**

What I did was deleting the plugins folder from:
- `root/plugins/`
- `root/platforms/android/platform_www/plugins/`
- `root/platforms/android/src/de/` (I didn't have other plugins from Germany)

After that I ran the command: `phonegap run android` again and the error was gone.

***
*plugins folder = `root/plugins/de.appplant.cordova.plugin.local-notification`

**Comment by vcajes** [comment] 2016-02-10 18:37
Same problem here

**Comment by liranhershko** [comment] 2016-02-16 10:38
Same issue for me :(

**Comment by amunters** [comment] 2016-02-18 22:55
me too....

**Comment by rodrix** [comment] 2016-02-21 20:25
me too

**Comment by rodrix** [comment] 2016-02-21 20:37
I solved temporaly this issue downgrading the plugin version:

> ionic plugin remove de.appplant.cordova.plugin.local-notification
> ionic plugin add de.appplant.cordova.plugin.local-notification@0.7.8

Hope this helps.

**Comment by amunters** [comment] 2016-02-22 22:56
Thanks for the hint Rodrix. I tried downgrading step-by-step and found that 0.8.2 works OK.
With 0.8.3 and 0.8.4 I'ḿ getting following errors:

COLOR_DEFAULT cannot be resolved or is not a field	Options.java	/MainActivity/src/de/appplant
/cordova/plugin/notification	line 262	Java Problem
DEFAULT_LIGHTS cannot be resolved or is not a field	Options.java	/MainActivity/src/de/appplant/cordova/plugin/notification	line 245	Java Problem
The method setColor(int) is undefined for the type NotificationCompat.Builder	Builder.java	/MainActivity/src/de/appplant/cordova/plugin/notification	line 130	Java Problem

**Comment by amunters** [comment] 2016-02-23 22:46
Found it: I was using an outdated version of android-support-v4.jar in my Java build path. Replaced it by the latest version. No build errors anymore!

**Comment by sebrojas14** [comment] 2016-03-11 02:14
How I replace the android-support-v4.jar? please help

**Comment by serdarde** [comment] 2016-03-31 03:58
I had the same problem today,

I am using facebook plugin and I tried to install "cordova-plugin-local-notifications". There is a conflict between those 2 plugin because facebook plugin uses the old version of android-support-v4.jar ...

After 6 hours fight(I shame of it..) I found solution for my app:

I found every single **android-support-v4.jar** file in my app (it is about 700kb) and changed it with new version. The new version is in **android-sdk\extras\android\support\v4**

I hope it will help for next victims..

**Comment by nickkenens** [comment] 2016-05-27 14:27
+1

**Comment by serdarde** [comment] 2016-05-27 14:56
@nickkenens Did you try my solution?

**Comment by k4rt2** [comment] 2016-08-01 07:01
I solved this issue removing file:
**/platforms/android/libs/android-support-v4.jar**

**Comment by rwillett** [comment] 2017-02-20 08:11
Is this still an issue otherwise I'll close it.

**Closed** 2017-02-22 07:29 UTC
Labels: android, Awaiting Information
