### ISSUE TITLE
I get the trigger event, but not the subscribe, and I don't see a foreground notification (ios10 branch)

### ISSUE THREAD

**Issue by GunslingerBara** [katzer/cordova-plugin-local-notifications#1385] opened 2017-09-22 21:17 UTC
Hello,

I am using the ios10 branch in order to show foreground notifications, but it just will not work. I have tried the "x" branch as well and that did not work either. My situation:

- The .on("trigger") event gets fired.
- The .on("schedule") event does NOT get fired.
- The callback for the .schedule() call does indeed get hit.
- Using the "x" branch does not fire the trigger event.
- When using the "x" branch, I made the necessary changes to get it working (eg: "trigger" instead of "at").
- The current 0.8.5 tag also does not work.
- hasPermission call always returns true (called on startup, when ionicPlatform is ready).
- I am using the cordova-plugin-firebase plugin by arnesson, specifically this commit: 01c872f726fcaf9ae0b72f15360f6f691ecdb5ef

## Your Environment

* Plugin version: ios10 branch (0.8.5), also tried latest "x" branch as of 9/22/17
* Platform: iOS
* OS version: 10.3.3
* Device manufacturer / model: iPhone 6 Plus
* Cordova version (```cordova -v```): 6.5.0
* Cordova platform version (```cordova platform ls```): iOS 4.3.2, Android 6.1.2
* Plugin config: Not sure what this is asking for?
* Ionic Version (if using Ionic): 1.3.2

## Expected Behavior

I should see a local notification while the app is in the foreground. Clicking on the notification should call the on("click") event.

## Actual Behavior

I don't see a local notification at all. Trigger event is fired, but schedule event is not.

## Steps to Reproduce

This is the call that I make to schedule a notification:
window.cordova.plugins.notification.local.schedule({
	id: id, // number
	at: datetime, // Date, set to "new Date()"
	title: title,
	text: text,
	data: data, // JSON object
	icon: "res://notification_icon.png",
	color: "FF5621"
}, function() {
	console.log("callback"); // I do see this
});

## Context

I expect a local notification to be shown while the app is in the foreground.

## Debug logs

No logs, but I can provide some if needed.

**Comment by katzer** [comment] 2017-10-30 12:02
@GunslingerBara I cannot reproduce... Scheduling a notification shows up the notification banner.

```js
window.cordova.plugins.notification.local.on('add', function() { console.log('add'); });
window.cordova.plugins.notification.local.schedule({ title: 'Title', text: 'text' });
```

Please re-open of that does not help. Use the master branch. The x branch has been merged into master.

**Closed by katzer** 2017-10-30 12:02 UTC

**Comment by GunslingerBara** [comment] 2017-11-01 20:57
@katzer This issue occurs specifically because of the cordova-plugin-firebase plugin by arnesson. If I have both plugins installed in a project, local notifications cease to work. If I uninstall the firebase plugin, they work again.
