### ISSUE TITLE
Calling .clear() from trigger event is not clearing notification

### ISSUE THREAD

**Issue by gotters** [katzer/cordova-plugin-local-notifications#1246] opened 2017-03-20 13:16 UTC
As per some other reported issues I am trying to clear the notification from within the trigger event.
I had this working at some point but now its completely stopped working.

I know my trigger event is firing and calling the LocalNotifications.clear() (when necessary) and I even get a success response from .clear() but the notification is still showing.

```
        LocalNotifications.on("trigger", (notification, state) => {
            console.log("Triggering notification (Page)",notification, state);

                  LocalNotifications.clear(notification.id).then((result)=> {
                      console.log('Successfully cleared',result);
                  }).catch((err)=> {
                      console.log('Failed clearing notification',err);
                  })
                  return;
               }
```

The only difference from when I had it working is that I see in the console that multiple trigger events are firing all of them are calling the .clear() for the same notification. Could this somehow be making a problem?

I am using ionic2
My notifications are scheduled in a service but the event listener is on a page - not sure if thats an issue or not. I could not put the trigger event listener into the same service because it was not firing!

**Comment by rwillett** [comment] 2017-03-20 18:14
Please fill in the template in #1188 as that gives useful information such as versions, plugins, what you have done etc.

**Comment by gotters** [comment] 2017-03-21 13:14
# Environment

Plugin version: latest
Platform: android
Device manufacturer / model: Nexus 5 - Android 7.0
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
OS: Windows 10
Node Version: v6.6.0
Xcode version: Not installed
OS: Windows 10


# Expected Behavior

Plugin should call event listener (trigger) code
Plugin should clear the notifcation when calling the clear() method

# Actual Behavior
The above only works when both the listener and the scheduling code are put onto a single page.
However the above does not work when scheduling notifications via a service and trying to listen to the events from within a service.

# Tell us what happens instead
Notifications are triggered and displayed however the event listener code in the service is never called.
Even if I move the event listener onto a page in which case it is called (sometimes multiple times if the page had been loaded a few times) the .Clear() method does not work.
Only when everything is within a single page does it all work.

# Steps to Reproduce
Create a simple service...
Add the event listener with .clear() method into the constructor of the service

```
  constructor() {

        LocalNotifications.on("trigger", (notification, state) => {
            console.log("Triggering notification ",notification, state);

            if(notification.id = 1000) {
              console.log('Clearing test');
              LocalNotifications.clear(notification.id).then((result)=> {
                  console.log('Successfully cleared test',result);
              }).catch((err)=> {
                  console.log('Failed clearing notification test',err);
              })
              return;
            }
```

In the service add a test notification method

```
  testNotify() {
            var now = new Date().getTime(),
            _5_sec_from_now = new Date(now + 5*1000);
            LocalNotifications.schedule( {
                id:  1000,
                title: AppUtil.APPNAME + ' - Testing Notify',
                text: 'This is a 5 sec test',
                at: _5_sec_from_now,
                sound: null
              });
          }
```

Create a simple page and assign testNofiy to a button on the page.

ionic Emulate Android
 - click the button - the notification will appear and the event trigger code above will never be called (validated by console logs)

Now move the event trigger listener into the page with the button
- Now the event listener will be called but the clear() method returns OK but does nothing - ie notification is not cleared

# Context
Everything works in a self-contained page but not when using services.

# Debug logs
There are No debug logs of error

**Comment by gotters** [comment] 2017-03-27 18:01
I completed template 6 days ago. Has this been reviewed?

**Comment by rwillett** [comment] 2017-03-28 10:27
This is not a review process. This is a community forum.

The template gives people who can help, more useful information as most people do not provide anywhere near the right level of information necessary to help.

I use Ionic 1 and do not have this problem at all, we have tested with Android 5, 6 and 7 BUT we don't use Ionic 2.Given what little I know of Ionic 2, I'd be surprised if this is a bug in their code as so many other things wouldn't work. I think this is something in the way you have created your pages, or perhaps a scoping issue. Since we don't use Ionic 2 and have no intentions of moving to Ionic 2 this year, we can't help much.

Other people may be able to advise. I think you have coded the pages wrong BUT thats just a guess. There's no Ionic code to comment on,

Rob

**Comment by gotters** [comment] 2017-03-29 09:17
I understand that its a community forum but noone will even look at the issue with a label of "No Template" or "Awaiting Information" so I was just hoping that those would have been reviewed by now.

Thank you for your comments regarding the issue.
I assuming in Ionic1 you are just setting up your event listeners on the rootScope - something which doesnt exist in Angular2. I have done a lot of research and also reproduced this issue in simple code examples so I dont think there is anything wrong with my code (although I would be happy if that was the case!)

I agree that it does sound like some kind of scoping issue but I am not getting any assistance on the ionic2 forum regarding this issue so was trying all avenues.

One final question...will the notifications work if the user never opened the app or is that only achievable with push notifications?

Thanks

**Comment by rwillett** [comment] 2017-03-29 09:59
Apologies, missed the "Awaiting Information". Its now gone.

What we find whats the best is when people provide a lot of information in a simple to use format that people can easily and quickly understand. The worst questions are "It doesn't work" with no explanation :) 

Your comment 

```
I assuming in Ionic1 you are just setting up your event listeners on the rootScope - something which doesnt exist in Angular2. I have done a lot of research and also reproduced this issue in simple code examples so I dont think there is anything wrong with my code (although I would be happy if that was the case!)
```

does indicate you know what you are talking about. You are correct, this is how it works in Ionic 1 and Angular. The fact you can reproduce the problem in a simple code sample (which wasn't clear from your comments), does tend to lead me to think there is some mutual incompatibility between the plugin and Ionic 2. 

We have not even looked at Ionic 2 as its only recently become stable (and I'm personally not convinced its that stable yet) and we have no intentions of doing so for six to nine months. I don't know if anybody has got this working with Ionic 2. I'm not the developer so can't say what it works with or not, what I will do is create a new tag "Ionic2" so that its slightly easier to track. I'll also have a look back through the issues and see if any of them are Ionic 2.

Sometimes the Ionic forums are good but a lot of the time, its difficult to get help. YMMV.

In answer to your last question, the app does NOT have to be running to receive local notifications. It must have been running to create the local notifications in the first place. Even if the app only uses push notifications (which we do), you have to open the app to register with Apple and hence the push notifications provider.  Is that what you meant? You can't create a local notification from another app for a second app (AFAIK), though with Android I'm never certain how far you can push it.

**Comment by gotters** [comment] 2017-03-29 10:57
Thanks for all the useful points and the ionic2 label.

I am going to deploy my app onto different devices and see if there is any difference in behaviour in this issue.

Thanks

**Comment by Tawpie** [comment] 2017-03-29 15:53
To your final question: no and no. The user must open the app in order for the local notifications to be scheduled. Similarly, push notifications will not work until the user has opened the app and the app has registered for and received a token from Apple—this token matches up the device with incoming push messages.

(and yep, I’d bet a nickel that you’re looking at a scoping issue!)

**Comment by gotters** [comment] 2017-03-29 16:43
I was asking whether the notification would trigger if the app was closed
for eg my open app sets up some scheduled notifications. Then I restart my
phone without opening the app. Will the notifications trigger. It sounds
like they will.

So any idea how to manage these scoping issues with ionic2?

**Comment by rwillett** [comment] 2017-03-29 16:45
Yes your notifications will trigger once they are scheduled and your app is closed. 

Restarting the phone without restarting the app is also fine, the notifications will trigger.

**Comment by gotters** [comment] 2017-03-29 17:01
Great. Still of no use until I get the event listeners triggering
Thanks

**Comment by gotters** [comment] 2017-03-29 20:12
I made a little bit of progress. I have tried a different Google API in my emulator and it looks like it may be working - ie running the event listener in a service is being called on trigger! Still need to run additional tests to confirm.

However the second problem still exists even when the trigger happens...namely that the .clear() method that I call seems to run successfully (ie it doesnt fail), but it also does not clear the notification! (see my code snipped above in the on trigger event)

Anyone have any idea what would stop the notification from clearing or how to investigate this further?

**Comment by rwillett** [comment] 2017-03-29 20:17
Your .clear() is a promise, my .clear() is a callback.

I happen to be working on our notifications so I have had a look at our functions to clear, we use a callback 

```
        	cordova.plugins.notification.local.clear(toClearArray , function() {
                    if (debugClearCongestionNotifications)
	            {
                     	ConsoleLog("ClearCongestionNotifications: Clear function success i = " + i);
			cordova.plugins.notification.local.getAll(function (notifications) {
                            ConsoleLog("cordova.plugins.notification.local.clear: notification Drawer is " + JSON.stringify(notifications));
	                });
                    }
                });
```

I know ours works, I didn't know there was a version of the plugin with promises.

Rob

**Comment by gotters** [comment] 2017-03-29 20:35
Thats interesting. I do know that the code has worked, again depending on where I put my event listener.
But I did see clear() working, and as a promise.

In any case there is something flaky going on because now my event listener is not being called anymore. I need to investigate further

**Comment by gotters** [comment] 2017-03-29 21:01
Look at this code.... within my on Trigger event listener I am wrapping my clear method in a .isTriggered method
```

`LocalNotifications.on("trigger", (notification, state) => {
     
        LocalNotifications.isTriggered(notification.id).then((res) => {
          console.log('Is notification triggered',res);
          LocalNotifications.clear(notification.id).then((result)=> {
              console.log('Successfully cleared test',result);
          }).catch((err)=> {
              console.log('Failed clearing notification test',err);
          })
        }).catch((err)=> {
            console.log('Failed checking if triggered',err);
        });

     
  });
````

The result I get back from isTriggered is FALSE!! 
This would explain why calling .clear() on the notification does nothing. 
Could there be some timing issue? ie even though its been triggered because the event has fired, its not yet fully registered and as a result the clear() operation will not take effect 
(even though I know when putting the event listener on a page the clear() did seem to work)

**Comment by rwillett** [comment] 2017-03-29 21:05
Why not rewrite it as a series of callbacks and see what happens?

**Comment by gotters** [comment] 2017-03-29 21:11
Its been implemented in typescript with a promise and not a callback, so it wont work

  static clear(notificationId: any): Promise<any>;
    /**
     * Clears all notifications
     * @returns {Promise<any>} Returns a promise when all notifications have cleared
     */

**Comment by rwillett** [comment] 2017-03-29 21:15
So the plugin you are using isn't really this one, but a wrapper round this one. Which version is it then? The phrase 'latest' is meaningless.

**Comment by gotters** [comment] 2017-03-29 21:24
Looks like 0.8.4
```

{
  "name": "de.appplant.cordova.plugin.local-notification",
  "cordova_name": "Cordova LocalNotification Plugin",
  "version": "0.8.4",
  "description": "Schedules and queries for local notifications",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/katzer/cordova-plugin-local-notifications.git"
  },
  "keywords": [
    "appplant",
    "notification",
    "local notification",
    "cordova",
    "ecosystem:cordova",
    "cordova-android",
    "cordova-ios",
    "cordova-windows"
  ],
  "platforms": [
    "ios",
    "android",
    "windows"
  ],
  "engines": [
    {
      "name": "cordova",
      "version": ">=3.6.0"
    },
    {
      "name": "cordova-plugman",
      "version": ">=4.3.0"
    },
    {
      "name": "cordova-windows",
      "version": ">=4.2.0"
    }
  ],
  "dependencies": {
    "cordova-plugin-device": "*",
    "cordova-plugin-app-event": ">=1.1.0"
  },
  "author": "Sebastián Katzer",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/katzer/cordova-plugin-local-notifications/issues"
  },
  "homepage": "https://github.com/katzer/cordova-plugin-local-notifications#readme"
}
```

**Comment by rwillett** [comment] 2017-03-29 21:29
Its not the latest then, thats 0.8.5.

However I suspect this version shouldn't cause a problem for Android.

I've no idea what they've done or changed to make it work (they may not have done anything).

If you can use this version and use callbacks, then it may be easier to debug. I don't use Ionic 2 so all I can do is guess.

**Comment by gotters** [comment] 2017-03-30 09:59
Thanks for all your help. Will have to dig further myself or try get help from the ionic team

**Comment by rwillett** [comment] 2017-03-30 10:05
I would not use their version, I would use the plugin here just for testing it out. The callbacks are trivial to use for testing and you are then using code that other people are using.

**Comment by gotters** [comment] 2017-03-30 10:42
ok will do

**Comment by gotters** [comment] 2017-03-30 14:38
Regarding my issue I am seeing something very interesting and wondering if you can test in your non-Ionic2 environments.

I created 2 notifications...one which is a once off and another which is scheduled to run daily
As follows:
```

                 var now = new Date().getTime(),

                 let _10_sec_from_now = new Date(now + 10*1000);
                 LocalNotifications.schedule( {
                     id:  1001,
                     title: AppUtil.APPNAME + ' - Testing Notify',
                     text: 'This is a 10 sec test - no period',
                     at: _10_sec_from_now,
                     sound: null
                   });


                   let _15_sec_from_now = new Date(now + 15*1000);
                   LocalNotifications.schedule( {
                       id:  1002,
                       title: AppUtil.APPNAME + ' - Testing Notify',
                       text: 'This is a 15 sec test every day',
                       at: _15_sec_from_now,
                       every: 'day',
                       sound: null
                     });

```

Within my event listener which called the clear() method I add the following code to view the list of triggeredIds. I expected to see both of the above 1001 and 1002

         LocalNotifications.getTriggeredIds().then((results) => {
            console.log('Triggered',results);
          })

But only 1001 appears in the list, ie the one which was once-off and not scheduled to run daily.
Likewise when I call .clear() on 1001 the notification is cleared but on 1002 it doesnt clear (seemingly because its not regarded as a triggered notification).

So assuming my assumption is correct, I would expect to see both notifications show up in the list of triggeredIds when each one gets triggered, even though one is a scheduled notification - is that correct?
And if so this seems to be related to the reason why .clear() is not working on the scheduled notification.

Let me know your thoughts. Thanks

**Comment by rwillett** [comment] 2017-03-30 15:11
There are known issues with ```every:``` and ```at:``` on IOS 10. 

That might be the problem.

**Comment by gotters** [comment] 2017-03-30 15:30
But I am in Android

**Comment by rwillett** [comment] 2017-03-30 15:36
Yes you are, I had forgotten...

**Comment by rwillett** [comment] 2017-03-30 15:36
We don't use ```every:``` and we have no issues on IOS 8,9 and 10 and Android 4, 6 and 7.

**Comment by gotters** [comment] 2017-03-30 16:06
So you're saying "every" is probably unreliable?

**Comment by rwillett** [comment] 2017-03-30 16:09
Nope, I'm saying we don't use it and other people have reported problems with ```every:``` and ```at:``` on IOS.

**Comment by rwillett** [comment] 2017-03-30 16:09
Take it out and see what happens.

**Comment by gotters** [comment] 2017-03-30 17:23
I mentioned above if I don't use "every" it works as expected. Or did you
mean take something else out?

Looks like I am blocked now. Not sure what the point is of notification
that can't be scheduled.

**Comment by rwillett** [comment] 2017-03-30 17:30
We do complex scheduling without every using ```every:```

We work out what we need to schedule and do send them all out. The limit on Android is quite high (512?) so you can easily schedule something at 9:00 for the next year without ever having to use ```every:```. 

IOS has a limit of 64 notifications so you *have* to be clever with your app anyway. 

Clearly only you can say what your usage is, but we've never needed every: and its never been an issue and we send a lot of local notifications on a daily basis.

**Comment by gotters** [comment] 2017-03-30 17:47
Ok I never considered that. Seems like a lot of unnecessary work for functionality that should already exist.
But will go forward with this.
Thanks

**Comment by gotters** [comment] 2017-04-01 19:36
Before moving ahead can you please just clarify the following for me:

- I want my app to work on Android, so assuming i build in my own scheduling will the regular once-off notifications work even in IOS or is there a problem even for "at" without using "every" given that you mentioned:
There are known issues with every: and at: on IOS 10.

- Sounds like issues have been acknowledged with "every" in IOS but not in Android. Although I am pretty sure I am seeing a bug here when using "every" even in Android (ie that its not properly registering as being triggered, and as such clearing doesnt work)
Should this be logged as a separate issue?

Thanks

**Comment by rwillett** [comment] 2017-04-01 20:21
We have more-or-less identical logic for both IOS and Android phones. 

The creation of notifications is identical for IOS and Android. We use ```at:``` and the same code for IOS and Android. It's not identical code, its the same code. 

The differences are in the way each OS and version of OS handles clear downs. The behaviour iof IOS and Android is different, so we have different functions to clear IOS 8/9, IOS 10 and Android. Also (from memory), querying produces different results from IOS 10 and IOS 8/9. This is not the plugin, just the way the OS works. 

We don't use ```every:``` for either IOS or Android so can't comment. I would say though that since you are using an old version of the plugin thats been customised for Ionic, its not clear if these are still present. If I was the author, I'd want a sample test case showing the Android not working with the latest version of the code before I looked at it.

**Comment by gotters** [comment] 2017-04-02 09:39
Ok thanks for the advice. Will see what I can do about a sample using newer
version

**Comment by rwillett** [comment] 2017-04-16 07:15
Is this now working?

**Comment by gotters** [comment] 2017-04-18 11:34
I got pulled into other issues. I will be returning to building out this
workaround in the next week or so.
Thanks

**Comment by gotters** [comment] 2017-04-26 20:32
Ended up implementing as discussed - ie setting up individual notifications and not using "every" and results seemed good. ie the clear() method is working when being called from within the trigger event.

However still seeing very inconsistent behaviour as to when the trigger event actually fires. When deploying to Android emulator and watching console sometimes it simply will not fire. Redeploying and it may start firing. 
Deploying to a real device (via app store) currently does not have the trigger event firing.
But I realize this may be an ionic integration issue and not the plugin itself. At this point I dont know how to figure that out.

If you have any guidance on this let me know.
Also am interested to know how you are setting up your batches of notifications. Since there are limits in IOS to how many you can create I assume you are creating batches of notifications for the next specified period of time and then at some later point in time recreating them in order to keep them current. 
Did you have a good strategy for when exactly to do that?

**Comment by rwillett** [comment] 2017-04-26 20:43
We've not had any problems with Android local notifications. They fire when we want them (to a few secs or minutes). Its no big deal if they are a few minutes late for us.

We don't tend to use the emulator as we are heavy users of GPS and whilst the Android emulators are better than the IOS ones, they are still pretty rubbish for GPS.

We use local notifications on our production IOS apps with no issues. We also use Ionic 1, not touched Ionic 2. 

We create batches of up to eight notifications, basically thats enough for us, the only way we can create any more is for the user to log on to the app and do things that create more local notifications. They can only create eight notifications at a time so we get round the limits through a sensible design. if the user doesn't reuse the app, then theres no need for local notifications, therefore not a problem.

**Comment by gotters** [comment] 2017-04-26 20:51
Thanks for the info.

By the way when i said there was inconsistent behaviour with the trigger event firing, I didnt mean that sometimes the notifications don't display. They are always displaying correctly.
I meant that I am watching the trigger event because some notifications have to be intercepted and cleared (for eg if the notification is a reminder to do a certain task, if the task has been done i want to clear the notification. Thats simplified...it gets a lot more complicated than that).
When the notification pops up I am seeing inconsistencies in that on some deployments the trigger event will fire and other times not - with no reasonable explanation.

Something somewhere is flaky! Thanks for all the info and advice!

**Comment by rwillett** [comment] 2017-04-26 20:54
OK, understood. We don't have that behavior. We use the notifications to remind the user to pay something. The user can delete the notification but we keep displaying it for another 10 minutes so there is no excuse for them to miss it. It also means if they do delete the notification by mistake, they get it back quickly.

**Comment by katzer** [comment] 2017-10-31 10:42
Please try out with 0.9-beta - that should work at least without Ionic.
But for now I am closing all ionic related tickets because they point to old code and/or Ionic.

**Closed by katzer** 2017-10-31 10:42 UTC
Labels: Ionic 2
