### ISSUE TITLE
Unknown property "firstAt in local-notification-util.js:120

### ISSUE THREAD

**Issue by salvatoreleone** [katzer/cordova-plugin-local-notifications#992] opened 2016-06-02 12:27 UTC
Hi,

this issue is back. Adding "firstAt" in the _defaults fixed it for me:

```
// Default values
exports._defaults = {
    text:  '',
    title: '',
    sound: 'res://platform_default',
    badge: 0,
    id:    0,
    data:  undefined,
    every: undefined,
    at:    undefined,
    firstAt:undefined //added by me
```

**Comment by stefanvangastel** [comment] 2016-09-05 08:43
Doesn't fix it for me. Keep getting same warning. @salvatoreleone what exact file did you change it in?

**Comment by rwillett** [comment] 2017-02-27 09:36
Is this still an issue? Its nearly six months old.

**Comment by rwillett** [comment] 2017-03-03 08:45
No update from original poster so closing.

**Closed by rwillett** 2017-03-03 08:45 UTC
Labels: Awaiting Information

**Comment by rafaellop** [comment] 2017-06-09 20:27
I can confirm the issue. Sample code:

```
cordova.plugins.notification.local.schedule({
                    id:     1,
                    title:  "title",
                    text:   "text",
                    every:  "day",
                    badge:  1,
                    led: "0000FF",
                    firstAt: nextNotifdate
                }); 
```

Console reports error:

```
Unknown property: firstAt			local-notification-util.js:122 
	exports.mergeWithDefaults	@	local-notification-util.js:122
	fn	@	local-notification-core.js:79
	(anonymous)	@	local-notification-util.js:208
	exports.hasPermission	@	local-notification-core.js:424
	exports.registerPermission	@	local-notification-core.js:442
	exports.schedule	@	local-notification-core.js:89
	exports.schedule	@	local-notification.js:62
	(anonymous)	@	app_controller_notifications.js:108
	(anonymous)	@	local-notification-util.js:208
	callbackFromNative	@	cordova.js:293
	(anonymous)	@	VM420:1
```

**Comment by mailmesalah** [comment] 2017-07-08 13:13
I think it might be because of wrong data fed to it, nextNotifdate might not be date formate or what ever the format firstAt property requires. i gave 1 and got the similar error, like undefined property (dont remember properly) firstAt. so when i gave 'var remVFromNow = new Date(now + (reminderValue * 1000 * 60));' that error was resolved it seems, any way it is working as i needed now. So it might be the Date format that you might need to focus.
