### ISSUE TITLE
Android notifications don't seem to work when app is killed, or when exited using back button

### ISSUE THREAD

**Issue by maory69** [katzer/cordova-plugin-local-notifications#766] opened 2015-12-01 18:56 UTC
Hi,

I'm using this plugin in order to implement local notifications in android.
I'm scheduling a notification to work everyday in a specific time. 
Now if I exit the app using the Home Button, then everything works properly and I get the notification in time. But if I exit the app using the Back button, and then I turn off the screen, waiting for the notification to pop. I will not get the notification (no sound or screen awakens) until I will open the screen again, even if the time that the notification was scheduled for already past.
And the biggest problem is that if I schedule a notification, and then I clear my recently used apps on android, I dont get the notification at all!

Help pleaseeeee

**Comment by ammichael** [comment] 2015-12-01 22:08
I just tried it here and still works even closing with back button.

**Comment by maory69** [comment] 2015-12-02 10:34
works as in, wakes up the screen, or like what happens to me, that I only get it when I turn on the screen.
and what if you "kill" the app?... I mean clear all the recently used apps in android? Does it work then?

Do I need any special settings/plugin to get it to work in background?

**Comment by maory69** [comment] 2015-12-02 10:49
ok so.. i'm using xiaomi redmi note 2 with MIUI os (build on top of android 5.0.1). I just saw that there is a setting for "allowed autostart apps", and I noticed that my app was turned off. so I turned it on, and schedule a notification, killed the app, and it worked!! I actually got the notification a minute later, which is weird (if anybody knows why I'd appreciate it), but at least it worked!
so my question now is how do I make my app get this permission in the beginning, so that my users will never have this problem. thanks!

**Comment by katzer** [comment] 2015-12-02 13:42
@maory69 
> I actually got the notification a minute later, which is weird (if anybody knows why I'd appreciate it), but at least it worked!

When Android is busy or less memory,... it will not trigger the notification in time.

> how do I make my app get this permission in the beginning

Maybe its a Xiaomi specific permission. Never heard about issue.

**Comment by katzer** [comment] 2015-12-02 13:44
If you have a programmatic solution you can post it here.

**Closed** 2015-12-09 10:28 UTC

**Comment by rupalpatel0008** [comment] 2016-11-28 10:34
I am also having this same issue on Redmi note 3, android 5.0.1

**Comment by suru1694** [comment] 2017-06-10 08:35
String manufacturer = "xiaomi";
        if(manufacturer.equalsIgnoreCase(android.os.Build.MANUFACTURER)) {
            **//this will open auto start screen where user can enable permission for your app**
            Intent intent = new Intent();
            intent.setComponent(new ComponentName("com.miui.securitycenter", "com.miui.permcenter.autostart.AutoStartManagementActivity"));
            startActivity(intent);
        }

**Comment by suru1694** [comment] 2017-06-10 09:34
but the problem is we are not able to get the status of setting that it is enable or not.please if any one find how to get the enable , disable status then post an answer

**Comment by abhishekptl** [comment] 2017-06-29 06:27
I also want to detect if Auto start is enabled or disabled for App programmatically in those customized android phone like xiomi, vivo, etc?

I was looking try to get some attribute which tell Autostsart is enabled or disabled for app using but can't get any such thing. Any suggestion.

>  PackageManager packageManager = getPackageManager();
>         Intent intent = new Intent();
>         intent.setAction(Intent.ACTION_BOOT_COMPLETED);
>         List<ResolveInfo> allBroadcast = packageManager.queryBroadcastReceivers(intent, 0);

**Comment by Gamehub123** [comment] 2019-08-07 09:58
cafa
