### ISSUE TITLE
cannot read property 'notification' of undefined

### ISSUE THREAD

**Issue by cincaw** [katzer/cordova-plugin-local-notifications#1596] opened 2018-05-04 18:28 UTC
Hi, I got error "cannot read property 'notification' of undefined " when I try to use simple code to show notification. The plugin already listed on cordova_plugin.js and already include cordova.js on my html file. Here is the sample file I try:
        cordova.plugins.notification.local.schedule({
		title: 'My first notification',
		message: 'Thats pretty easy...'
	});

## Your Environment

* Plugin version:0.9.0-beta.3
* Platform:Android
* OS version:7.0.0
* Device manufacturer / model:Samsung Galaxy S8
* Cordova version (```cordova -v```):8.0.0
* Cordova platform version (```cordova platform ls```):7.0.0
* Plugin config
* Ionic Version (if using Ionic)

## Expected Behavior

Notification should show up

## Actual Behavior

Notification doesn't show up

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. Starrt App
  2. After deviceready event,  call notification
  3. Notification doesn't show up

## Context

I want to try simple notification like this :
cordova.plugins.notification.local.schedule({
		title: 'My first notification',
		message: 'Thats pretty easy...'
	});

## Debug logs

Uncaught TypeError: Cannot read property 'notification' of undefined
    at Object.App.deviceready (App.js:9)
    at Object.App.init (App.js:31)
    at HTMLDocument.<anonymous> (App.js:36)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)

**Comment by jonutz** [comment] 2018-05-10 14:07
The plugin was not installed properly, you are right

`cordova plugin add cordova-plugin-local-notification`

and then

```
cordova platform add android 
cordova build
```

withe the following 7 similar errors:

```
notification\Notification.java:34: error: cannot find symbol
import android.support.v4.util.ArraySet;
                              ^
  symbol:   class ArraySet
  location: package android.support.v4.util 
```

**Comment by rwillett** [comment] 2018-05-10 14:20
Impossible to say what the problem is as there's no context. I also don't use Windows. It may be that you have the wrong Android SDK but thats a guess. 

The template is there for a reason. Fill it out properly so we have some idea what you are doing, fragments of code or fragments of error messages are pretty much useless.

**Comment by rwillett** [comment] 2018-05-10 17:57
Closed as original issue resolved

**Closed by rwillett** 2018-05-10 17:57 UTC
