### ISSUE TITLE
Build bug with Cordova 5.1.1

### ISSUE THREAD

**Issue by calebeaires** [katzer/cordova-plugin-local-notifications#676] opened 2015-09-17 13:24 UTC
```
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/calebeaires/Android/sdk/build-tools/23.0.1/dx --dex --no-optimize --output /Users/calebeaires/Sites/nature/platforms/android/build/intermediates/dex/debug --input-list=/Users/calebeaires/Sites/nature/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)

```

**Comment by colonelchlorine** [comment] 2015-09-18 01:01
I'm also getting a build bug with 5.1.1 for Android. It reads like this though:

```
platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
    webView.evaluateJavascript(js, null);
           ^
symbol:   method evaluateJavascript(String,<null>)
location: variable webView of type CordovaWebView
```

**Comment by colonelchlorine** [comment] 2015-09-18 01:02
Nm, that seems to match with case #660

**Comment by calebeaires** [comment] 2015-09-18 18:52
This guy solved the problem

https://github.com/excendia/cordova-plugin-local-notifications

**Comment by roysG** [comment] 2015-09-19 18:35
sorry, but i get error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

**Comment by katzer** [comment] 2015-12-09 12:49
Build failures with `cordova build android` have been fixed within the last commits and minor updates.

@calebeaires 
> Execution failed for task ':dexDebug'.

Can also be a problem with `Push Plug-in` or `Facebook Plug-in`

@roysG 
> Could not find any version that matches com.android.support:support-v4:+

Sounds like you haven't installed the `Android Support Repository`

**Closed by katzer** 2015-12-09 12:49 UTC

**Comment by bluesliverx** [comment] 2016-03-12 15:39
Future note for self: this could also be caused by the crosswalk plugin on phonegap build which at points has included the support lib in its own jar file.  This has been fixed as part of a PGB-based crosswalk plugin: https://github.com/phonegap/phonegap-plugin-push/issues/199
