### ISSUE TITLE
Android : Notification not shown when app is not running / swiped away from recent

### ISSUE THREAD

**Issue by natanraj** [katzer/cordova-plugin-local-notifications#1150] opened 2016-11-22 08:04 UTC
I have this problem of notification not triggered when app is not in the running state (neither in the background). Is it device specific ? I have a Xiaomi device. If yes, how to overcome this ?

I got this due to a permission issue in Xiaomi and if i enable it through Device security settings, it works. Is there any way how we can set this work ?

**Comment by rwillett** [comment] 2016-11-25 09:10
Local notifications do work in the background on 'most' Android devices. We have a specific test case for notifications firing when app is terminated. 

You need to provide more information, e.g. code, versions of Android, versions of plugins, adb output etc to get more help.

Rob

**Comment by natanraj** [comment] 2016-11-25 11:22
@rwillett You are right. I just tested this by scheduling a local notification and then swiped away the app from active list. Few minutes late I got the local notification shown in my tray.

One question. When the local notification is triggered & shown,  does this mean the app has become active ? What if , the user has in between uninstalled it ?

**Comment by rwillett** [comment] 2016-11-25 11:35
For some reason I can't see your comment in any of my browsers! Odd!

>> @rwillett You are right. I just tested this by scheduling a local notification and then swiped away >> the app from active list. Few minutes late I got the local notification shown in my tray.

>> One question. When the local notification is triggered & shown, does this mean the app has 
>> become active ? What if , the user has in between uninstalled it ?

Anyway, no, the application has not become active when the scheduled notification appears if the app is already terminated

No idea on the user uninstalling the app in the time between it being scheduled and the scheduled time. Suggest you test it and see :)

Rob

**Comment by natanraj** [comment] 2016-11-25 11:38
hi Rob. I removed the comment, as it appeared to be working when I set the permissions for auto-restart in my Xiaomi Phone. I misunderstood that it is working, but once i removed the auto-restart it didn't work. So the issue is still there.
Is it something to do with any manifest entries ? I read soemwhere like this. 
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
Please bear with me, I am new to all these.

**Comment by rwillett** [comment] 2016-11-25 12:25
@natanraj 

1. Please don't remove comments. It makes things very confusing. I thought I had browser issues and couldn't work out what was going on. 

2. We never touch the AndroidManifest.xml file directly. All of our config is done through the config.xml file. I've just looked and we have nothing in config.xml to do with notifications permissions. An internet search on android.permission.RECEIVE_BOOT_COMPLETED doesn't seem to have anything to do with this.

We don't have a Huawei phone so can't see what it does. Since your first post says you solved this through Device security settings I'm unclear as to what your problem actually is.

Since you are new to this, you need to understand how to report issues. You need to be clear about what exactly you are trying to do and be able to state it,  you need to provide more information such as code, what have you tried, versions of Android, as an aside we refuse to touch Android before 5.0 as its too fragmented and idiot vendors screwed up Android with their changes. Android 5.0 is far better. You need to show what you have tried to do and any error messages. 

You need to be concise and clear about things. It may well take an hour to write what your problem is. Writing out your problem also helps you understand the problem you are trying to solve and forces you to be analytical in your approach to resolving the issue. It also shows that you have thought through the problem and the problem is real and not just bad coding on your part.

Rob

**Comment by evandrojr** [comment] 2017-01-23 09:10
I had this issue with Asus zenfone 2, but I allowed the app to auto start and it fixed the problem. Asus has a software that blocks other software to save battery. Shit!

I wonder how the other alarm software handle that, so no user action is required.

**Comment by rwillett** [comment] 2017-01-23 09:14
Thanks. Lets close this issue down now.

**Closed** 2017-02-15 17:03 UTC
