### ISSUE TITLE
Crashes on iOS 11 GM (unrecognized selector sent to [__NSCFBumber un_logDigest]) -- with 'fix'

### ISSUE THREAD

**Issue by Tawpie** [katzer/cordova-plugin-local-notifications#1379] opened 2017-09-14 20:11 UTC
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

Existing apps that work on iOS10 crash on iOS11.

## Your Environment

* Plugin version: (customized fork to add LED control and incorporate early iOS10 fixes) de.appplant.cordova.plugin.local-notification 0.8.4+ledControl+spk0611iOS10Changes
* Platform: iOS
* OS version: iOS 11GM (11.0 15A372)
* Device manufacturer / model: iPhone 6 simulator (Xcode9) iPhone 6S+, iPod Touch 6th Gen
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```):
```(!746)-> cordova platform ls
Installed platforms:
  android 6.1.2
  ios 4.1.1
Available platforms: 
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  osx ~4.0.1
  webos ~3.7.0
```
* Plugin config
```
(!744)-> cordova plugins ls
cordova-custom-config 3.1.2 "cordova-custom-config"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-background-task 0.2.0 "Background Task"
cordova-plugin-camera 2.3.2-dev "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-email-composer 0.8.3 "EmailComposer"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-insomnia 4.2.0 "Insomnia (prevent screen sleep)"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-navigationbar 1.0.31 "Cordova NavigationBar plugin"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.3.2-dev "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.4+ledControl+spk0611iOS10Changes "LocalNotification"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-push 1.8.4 "PushPlugin"
```
* Ionic Version (if using Ionic)

## Expected Behavior

things work as they have for some time

## Actual Behavior

Crashes:

```
2017-09-14 12:44:44.238895-0700 xxx[26031:966628] -[__NSCFNumber un_logDigest]: unrecognized selector sent to instance 0xb00015e81ec0c553
2017-09-14 12:44:44.242338-0700 xxx[26031:966628] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber un_logDigest]: unrecognized selector sent to instance 0xb00015e81ec0c553'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001033941cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000102cc8f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000103414914 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000103317178 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000103316b58 _CF_forwarding_prep_0 + 120
	5   UserNotifications                   0x0000000104361b9c -[UNUserNotificationServiceConnection addNotificationRequest:forBundleIdentifier:withCompletionHandler:] + 280
	6   UserNotifications                   0x000000010435e2de -[UNUserNotificationCenter addNotificationRequest:withCompletionHandler:] + 113
	7   2Morrow                             0x00000001009c9fb4 -[APPLocalNotification fireEvent:notification:] + 1572
	8   2Morrow                             0x00000001009c5740 __33-[APPLocalNotification schedule:]_block_invoke + 640
	9   libdispatch.dylib                   0x00000001052373f7 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000010523843c _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010523d352 _dispatch_queue_override_invoke + 1458
	12  libdispatch.dylib                   0x00000001052441f9 _dispatch_root_queue_drain + 772
	13  libdispatch.dylib                   0x0000000105243e97 _dispatch_worker_thread3 + 132
	14  libsystem_pthread.dylib             0x00000001056fb5a2 _pthread_wqthread + 1299
	15  libsystem_pthread.dylib             0x00000001056fb07d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Steps to Reproduce

1) upgrade to iOS11GM
2) launch app

## Context

our scheduling code. Scheduling done in the callback from cancelAll. Notifications in the gaMultiRemindersForKatzerLNPlugin array (yes, thank goodness for autocomplete)
```
cordova.plugins.notification.local.cancelAll(function scheduleAllRemindersViaKatzer() {
    cordova.plugins.notification.local.schedule(gaMultiRemindersForKatzerLNPlugin);
});
```

## Debug logs

see above

  * ios XCode logs
  * Android: $ adb logcat

===============================
NOTE: I can make it not crash and schedule notifications, 
but it doesn't make sense why from an outsider's view.
===============================

To stop the crash, edit APPLocalNotification.m and comment out the following lines (you're removing the adding of the notification request, there will now be some unused variable warnings):
```
/// 3. schedule localNotification
        UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
        [center addNotificationRequest:request withCompletionHandler:^(NSError * _Nullable error) {
            if (!error) {
                NSLog(@"add NotificationRequest succeeded!");
            }
        }];
```

I would think that this would prevent the notification from being scheduled at all. *not the case*. The notification is scheduled and fires on schedule. Go figure.

The implication is that the notification request is getting added somewhere else?

**Comment by Tawpie** [comment] 2017-09-15 00:17
*** CAUTION ***

This approach to fixing this error has NOT BEEN WELL TESTED on devices that aren't running iOS11. Until more folks have a chance to verify that it's safe I certainly wouldn't use it in production at all. Ever!

*** you have been warned! ***

**Comment by Tawpie** [comment] 2017-09-15 00:31
Also, the so-called 'fix' may have side effects.

**Comment by hoonblizz** [comment] 2017-09-20 21:14
Thank you for the post.

**Comment by arcaderob** [comment] 2017-09-21 18:14
@Tawpie I have tried your fix and it does work with the notification, but it does not play the specified alert sound file specified.
I agree that it seems likely that there are at least two places where the notification is being set as commenting out that code still allows the notification to be set and fire correctly. It would appear, though, that the sound is fired and/or set in another place.
I am currently reviewing the code in an attempt to find where the sound is applied.

(Testing on iOS9 and iOS11)

**Comment by yjukaku** [comment] 2017-09-21 20:03
I ran into this same issue, but I (thought I) narrowed it down using the debugger to line 724 in `AppLocalNotification.m`

```
        if(notification.userInfo!=nil && [notification.userInfo objectForKey:@"id"]!=nil) {
            identifier = [NSString stringWithFormat:@"%d", [notification.userInfo objectForKey:@"id"]];
        }
```

If anyone has a fix for this issue, please do chime in.

**Comment by arcaderob** [comment] 2017-09-21 22:29
@Tawpie @hoonblizz @yjukaku I have found that the issue is this line:

`UNNotificationRequest *request = [UNNotificationRequest requestWithIdentifier:identifier content:content trigger:trigger];`

`requestWithIdentifier` expects NSString. The error is being thrown when it receives NSNumber. I believe that this parameter is the ID that we give to the notification object. We define it as an integer and it is breaking in the code.

I am still looking into, but I wanted to share my finding so that you can use that information to work on a possible solution.

**Comment by arcaderob** [comment] 2017-09-21 22:46
Working with the findings of @yjukaku change line 724 to:

`identifier = [NSString stringWithFormat:@"%@",[notification.userInfo objectForKey:@"id"]];`

**Comment by Tawpie** [comment] 2017-09-22 14:19
Thank you for looking into this, I'll give it a whirl on my next round of releases. I also use an int/number as the ID, there was a time when I believed the ID needed to be a string but that was some time ago! Seems it's back.

Not testing, just looking at the code in APPLocalNotification.m:491 or thereabouts is a call to a method that I can't find but its name implies it's also scheduling. The code calls the `fireEvent` method _after_ it calls `scheduleLocalNotification`

```
#pragma mark -
#pragma mark Core Logic

/**
 * Schedule the local notification.
 */
- (void) scheduleLocalNotification:(UILocalNotification*)notification
{
    [self cancelForerunnerLocalNotification:notification];
    [self.app scheduleLocalNotification:notification]; <<<--- can't find this!
}
```

**Comment by katzer** [comment] 2017-10-30 12:09
@Tawpie Is that still crashing with latest master branch (0.9-beta)?

**Comment by katzer** [comment] 2017-11-01 10:20
Please reopen if its still an issue.

**Closed by katzer** 2017-11-01 10:20 UTC
Labels: feedback
