### ISSUE TITLE
Takes too long to show notification

### ISSUE THREAD

**Issue by deepakbandela** [katzer/cordova-plugin-local-notifications#1227] opened 2017-02-28 13:22 UTC
Your Environment

Plugin version: 0.8.4
Platform: Android
OS version: 6.0
Device manufacturer / model: Moto G3 / Motorola
Cordova version (cordova -v): 6.4.0

Cordova platform version (cordova platform ls):
Your system information:
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002

Plugin config
<plugin name="de.appplant.cordova.plugin.local-notification" spec="~0.8.4" />

Expected Behavior
Local Notification takes around 5-6 seconds to display

Tell us what should happen
Local Notification should be displayed instantly

Actual Behavior
slow notification

Tell us what happens instead

Steps to Reproduce
just a notification scheule takes long time

Reproduce this issue; include code to reproduce, if relevant
LocalNotifications.schedule({
  id: 1,
  text: 'Single ILocalNotification',
  title: 'title',
  data: { secret: key }
});

Context
Want to show notifications on my events

**Comment by rwillett** [comment] 2017-02-28 14:34
Fill out the template in #1188.

As an aside Android doesn't guarantee immediate delivery.

**Comment by deepakbandela** [comment] 2017-03-01 08:52
Updated the defect description

**Comment by rwillett** [comment] 2017-03-01 08:56
Thanks for this, but as I said before, Android doesn't guarantee immediate delivery.

It would be interesting to know what slow means. 0.1 sec late, 1 sec late, 10 secs late, 1 minute late, 10 minutes late etc. One person's slow is another persons fast.

We use the local notifications and we see Android coming in 1-3 minutes behind the same test on IOS. We're not that bothered as our use case doesn't need millisec accuracy. Since push notifications aren't guaranteed to be on time either, if you require a notification to be highly accurate (whatever that means), you might be out of luck.

**Comment by rwillett** [comment] 2017-03-08 19:14
Closed as notification plugin working as designed.

**Closed by rwillett** 2017-03-08 19:14 UTC
Labels: android, Awaiting Information
