### ISSUE TITLE
Plugin crashes app on iOS during startup. 

### ISSUE THREAD

**Issue by epoplavskis** [katzer/cordova-plugin-local-notifications#852] opened 2016-01-26 21:26 UTC
Hi, after adding the plugin, when running app on ios (android is fine) the plugin crashes the app with 'BAD_ACCESS' error. 
<img width="886" alt="screen shot 2016-01-26 at 9 14 55 pm" src="https://cloud.githubusercontent.com/assets/3270444/12595379/d1a7da92-c472-11e5-8a2d-aa3e40415d90.png">

I did little bit of snooping around and found that this should be fixed by dependency cordova-plugin-app-event in 1.1.0 version, but i can confirm that this is the version i have and i still receive this error. 
Would really appreciate if you could help me solve this issue. 
Thanks

**Comment by aks0020** [comment] 2016-01-28 05:26
I am facing same issue :+1:

**Comment by RichardLewin87** [comment] 2016-02-08 14:47
Got the same issue here too.

**Comment by GitRubb** [comment] 2016-02-10 20:22
I am facing same issue :+1:

**Comment by liranhershko** [comment] 2016-02-15 09:35
Hi everyone.
The issue is apparently caused by the dependent cordova-plugin-app-event plugin.
As for now, the cordova-plugin-app-event (ver 1.1.0) has a [pending pull request](https://github.com/katzer/cordova-plugin-app-event/pull/4) that fixes this issue.
Until it will be merged you can simply follow the changed files to see what to change.
But if thats too much for ya :) just replace the **exchange_init_methods** function in CDVPlugin+APPAppEvent.m file to
```
+ (IMP) exchange_init_methods
{
    IMP swizzleImp = (IMP) swizzled_pluginInitialize;
    Method origImp = class_getInstanceMethod(self, @selector(pluginInitialize));

    if (method_getImplementation(origImp) != swizzleImp) {
        return method_setImplementation(origImp, swizzleImp);
    }
    return NULL;
}
```
That worked for me.
Good luck.

**Comment by iadc2005** [comment] 2016-02-17 08:19
still I will crash, I don't know why. But if I remove some other plugins, it will work even if without changing the codes. So, i was really confused.

**Comment by epoplavskis** [comment] 2016-02-17 10:21
Hi, i've tried rebuilding the app (by removing all plugins and platforms folder, then rebuilding again) and this plugins seems to work perfectly now on ios. Wonder if this is caused by incompatibility with older version of some other plugin.

**Comment by rwillett** [comment] 2017-02-16 20:49
Is this still an issue or can it be closed ? Its nearly a year old.

**Closed** 2017-02-22 07:31 UTC
Labels: Awaiting Information, bug, ios
