### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by LukePulverenti** [katzer/cordova-plugin-local-notifications#575] opened 2015-05-29 22:04 UTC
java.lang.StringIndexOutOfBoundsException: length=65; regionStart=0; regionLength=-1
	at java.lang.String.startEndAndLength(String.java:504)
	at java.lang.String.substring(String.java:1333)
	at de.appplant.cordova.plugin.notification.AssetUtil.extractResourceName(AssetUtil.java:407)
	at de.appplant.cordova.plugin.notification.AssetUtil.getUriFromRemote(AssetUtil.java:259)
	at de.appplant.cordova.plugin.notification.AssetUtil.parse(AssetUtil.java:118)
	at de.appplant.cordova.plugin.notification.Options.parseAssets(Options.java:131)
	at de.appplant.cordova.plugin.notification.Options.parse(Options.java:80)
	at de.appplant.cordova.plugin.notification.Manager.schedule(Manager.java:81)
	at de.appplant.cordova.plugin.localnotification.LocalNotification.schedule(LocalNotification.java:215)
	at de.appplant.cordova.plugin.localnotification.LocalNotification.access$000(LocalNotification.java:49)
	at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by LukePulverenti** [comment] 2015-05-29 22:04
My code looks like this:

            window.cordova.plugins.notification.local.schedule({

                id: WebNotifications.lastId,

                title: data.title,
                text: data.body,
                icon: data.icon
            });


where data.icon is an image url.

**Comment by Eusebius1920** [comment] 2015-06-20 20:46
I think this error is caused by wrong parsing the path.
You have two choices:

1.) Make sure that your path doesn't look like this:
some/path.with/dot/inTheMiddle/notAtTheEnd

2.) Make sure that your resource file has a proper file extension:
not image, but rather image.png

Fix:
I think, line 406 in AssetUtil.java should be
```java
if (drawable.contains(".")) {
  drawable = drawable.substring(0, drawable.lastIndexOf('.'));
}
```
instead of
```java
if (resPath.contains(".")) {
  drawable = drawable.substring(0, drawable.lastIndexOf('.'));
}
```
This would fix the issue.

**Comment by LukePulverenti** [comment] 2015-06-20 20:47
Yes you're correct. The code is assuming a filename can be easily parsed from the url. I submitted a pull request to address:

https://github.com/katzer/cordova-plugin-local-notifications/pull/588

**Comment by Eusebius1920** [comment] 2015-06-20 20:50
Ah right, I didn't see this pull request, but I also stumbled across this.
So I just wanted to let you know here, in case a third person encounters that problem.

**Comment by katzer** [comment] 2015-12-25 11:03
PR has been merged in. Tks

**Closed by katzer** 2015-12-25 11:03 UTC
