### ISSUE TITLE
It is not working on iOS 11.2 or iPhoneX

### ISSUE THREAD

**Issue by Sampath-Lokuge** [katzer/cordova-plugin-local-notifications#1559] opened 2018-03-25 03:14 UTC
**Config.xml**

` <plugin name="cordova-plugin-local-notification" spec="0.9.0-beta.2" />`

**Ionic info:**

```
cli packages: (C:\Users\lok\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.10.0
    npm               : 3.10.10
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk

Misc:

    backend : pro
```

I have installed the plugins like so:

```
ionic cordova plugin add cordova-plugin-local-notification
npm install --save @ionic-native/local-notifications
```

**Code:**

**app.component.ts**

```
constructor(){
 this.platform.ready().then(() => {
    timer(60000, 60000).subscribe(val => {//schedule Notification
      const hours = moment().format("H");
      const minutes = moment().format("m");
      if (hours == '10' && minutes == '1') this.scheduleNotification();
        });
    this.localNotificationHandler();
 });
}

scheduleNotification() {
    forEach(this.authenticationProvider.member.projects, (project: Project) => {
      forEach(project.transactions, (transaction: Transaction) => {
        if (transaction.dueOn != null && moment(transaction.dueOn).format('YYYY-MM-DD') == moment().format('YYYY-MM-DD')) {
          const id = random(1, 1000);
          cordova.plugins.notification.local.schedule({
            id: id,
            title: 'Due Today',
            text: `Payment for ${transaction.category.name}: ${transaction.description} of ${Number(transaction.totalPrice).toLocaleString()} is due today.`,
            data: { transaction: transaction, project: project },
            trigger: { every: { hour: 10, minute: 1 } },
          });
        }
      });
    });
  }

  localNotificationHandler() {
    this.localNotifications.on('click', (notification, state) => {
      const data = notification.data;
      const transaction = data.transaction;
      const project = data.project;
      this.goToEditTransaction(transaction, project);
    });
  }

```

It is working fine on the same day if an app goes to background mode few hours (less than 4 hours) on android device. But it is not working on iOS 11.2 or iPhoneX. On the Android device itself, we cannot trigger the click event. If we clicked the notification It opens the app again with a splash screen and goes to the desired screen (i.e. Edit ) without relevant data. That is useless since we need data for the edit screen.Could you tell me how to solve these issues? 

**Same sort of issue:** https://forum.ionicframework.com/t/ionic-local-notification-trigger-call-back-is-not-working-when-app-is-in-background-for-a-while/114925

**Comment by Sampath-Lokuge** [comment] 2018-03-29 06:43
Could you please see this? @katzer  @rwillett

**Comment by rwillett** [comment] 2018-03-29 08:57
Is this the Ionic version of the plugin or the plugin installed from here?

**Comment by mardugas** [comment] 2018-03-29 19:29
related to #1562

**Comment by Sampath-Lokuge** [comment] 2018-03-30 08:31
@rwillett I have used this:

`ionic cordova plugin add cordova-plugin-local-notification`
`npm install --save @ionic-native/local-notifications`

**Comment by Sampath-Lokuge** [comment] 2018-03-30 08:33
@mardugas Have you found the workaround?

**Comment by mardugas** [comment] 2018-03-30 11:41
not yet - any suggestions are welcome

**Comment by rwillett** [comment] 2018-03-30 13:40
This looks like the Ionic wrapped version of this plugin.

I'd dump that and try the version on this site. 

I'd also turn your code into the simplest possible code and try that. I'd also change the trigger to be a simple trigger 10 secs, so drop the every: field, in the future and work upwards from there.

**Comment by Sampath-Lokuge** [comment] 2018-03-31 06:47
Is this not working due to ` timer` background thread? @rwillett 

This:

```
constructor(){
 this.platform.ready().then(() => {
    timer(60000, 60000).subscribe(val => {//schedule Notification
      const hours = moment().format("H");
      const minutes = moment().format("m");
      if (hours == '10' && minutes == '1') this.scheduleNotification();
        });
    this.localNotificationHandler();
 });
}
```

**Comment by rwillett** [comment] 2018-04-01 17:26
Times do not work on the background on IOS. You cannot schedule a notification using a background timer as the moment the app goes in the background, the JavaScript timer stops. 

The Xcode simulator does not emulate the real IOS OS and keeps background timers running. 

As said before, strip your code back and start with something simple and work your way up to something complicated.

Rob

**Comment by JanBrinker** [comment] 2018-04-09 19:59
Might have found the solution for this in the dependency plugin app-event: https://github.com/katzer/cordova-plugin-app-event/issues/14

**Comment by JanBrinker** [comment] 2018-04-09 20:12
Actually I take it back. I fiddled around with the app-event plugin and it seems like there are quite a few more things in this plugin that need to be executed by the main thread. But I don't know whether this will solve everything.

**Comment by ourarash** [comment] 2018-04-17 21:04
I have the same issue with ios 11.3. I use the original basic cordova example. When I run the example, nothing happens. I don't get any notifications. However, remote notifications work, so the problem is not with certificates.

**Comment by rwillett** [comment] 2018-04-18 07:48
I've just tested this again on iPhone 5s running 11.2.6 and sent a local notification and it works fine.

Certificates are nothing to do with this at all, certificates are not needed for local notifications. 

I have no idea what Ionic do to the plugin. I do know that using 
```
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
```
and ionic 1

and this production code which I have just pulled directly from our local git repository. The code simulates what a remote notification looks like, has a data field and a small icon. We use it for demos. This code works and has been working with exactly the same local notification code for two years. 

```
    function SendDummyNotification() {
	var debugSendDummyNotification = debugFalse;
        var whatAmI = WhatAmI("SetupCongestionNotificationReminders");
        var d          = new Date();
        var now        = d.getTime();
        var year       = d.getFullYear();
        var month      = d.getMonth();
        var day        = d.getDate();
	var reminder0  = new Date(now + 10 * 1000);

        var notifications = [ { id: GetNotificationIdAndIncrement() ,
				sound: "" , // Turn the sound off
                                trigger: { at: reminder0 } ,
                                data: { type: "DisruptionNotification" , disruptionId: -1 } ,
                                text: "[A102] Blackwall Tunnel Southern Approach (S/B) - The carriageway is blocked southbound. Collision between two\
 cars. Carriageway blocked. Police on scene are removing vehicles. Expect long delays." ,
                                smallIcon: "res://pw_notification.png"
                              }];

        if (whatAmI === "android_app" || whatAmI === "android_simulator")
        {
            for (var i = 0 ; i < notifications.length ; i++)
            {
         	notifications[i]["smallIcon"] = "res://pw_notification.png";
            }
	}

        if (debugSendDummyNotification)
            ConsoleLog("SendDummyNotification: " + JSON.stringify(notifications));

        cordova.plugins.notification.local.schedule(notifications , function () {
            if (debugSendDummyNotification)
                ConsoleLog("SendDummyNotification: schedule callback OK");
        });
    }
```

It works find and a local notification is sent 10 secs later.

I am closing this thread as the original poster has not responded in nearly 17 days, If people still have a problem then they need to **raise their own thread and fill the template in**. Simply saying me too adds zero value to the thread as invariably people have done things differently. The template is there for a reason use it!

I strongly suspect the Ionic plugin is at fault and people should use the plugin from this repo.

Rob

**Closed by rwillett** 2018-04-18 07:48 UTC

**Comment by prashant37** [comment] 2018-04-19 20:52
@ourarash well for foreground I am using the socket connection and raising notification using this katzer plugin. There is a conflict between these two plugins and it is frustrating.

**Comment by ddralves** [comment] 2018-07-23 09:15
Please see: https://github.com/katzer/cordova-plugin-local-notifications/issues/1626

**Comment by YeisonVelez11** [comment] 2018-12-15 06:09
@ddralves  @Sampath-Lokuge   I am using IONIC 1 and I am having the same problem...  I'm trying to generate local notifications in the background. they work on an iphone6 but on an iphone xr nothing happens. I'm testing them in a simulator.
