### ISSUE TITLE
On click event not triggered on iOS 

### ISSUE THREAD

**Issue by Piranya** [katzer/cordova-plugin-local-notifications#1082] opened 2016-08-25 14:18 UTC
Hi,
On iOS Notifications are displayed correctly, but when I click on it it just opens an app and not triggers associated event. On Android all is working fine.

**Comment by NateOwen** [comment] 2016-08-31 22:02
Same here with iOS.

**Comment by plantastika** [comment] 2016-09-03 07:04
anyone has a fix to this issue?

**Comment by plantastika** [comment] 2016-09-05 23:16
same problem in iOS, here the code

    cordova.plugins.notification.local.schedule({
    id: 123,
    text: 'This is my notification',
    sound: sound,
    badge: 1
    });

and the click...

cordova.plugins.notification.local.on("click", function (notification) {
 alert("user clicked on notification");
  });


try this too but does not work either

 cordova.plugins.notification.local.on("click", function (notification) {
        if (notification.id == 123) {
    alert("user clicked on notification");
        }
    });

**Comment by NateOwen** [comment] 2016-09-09 22:52
I'm on Phonegap Build and I got this to work:

`var localnotificationsetup = false;
function setupLocalNotifications()
{
	if(!localnotificationsetup)
	{
		window.plugin.notification.local.on("trigger", function (notification, state) { alert('trigger ' + notification.id);  }, this);
		window.plugin.notification.local.on("click", function (notification, state) { alert('onclick' + notification.id);  }, this);
		localnotificationsetup = true;
	}
}`

This code works for me if I call setupLocalNotifications() when I create a new schedule window.plugin.notification.local.schedule, but doesn't seem to work if I do it at "deviceready".  Specifically what made it work was adding the scope of "this" on the local.on call.

**Comment by rwillett** [comment] 2017-04-10 06:45
Is this still an issue? if so update with template in #1188.

**Comment by rwillett** [comment] 2017-04-15 09:13
Closed as no update from Original Poster

**Closed by rwillett** 2017-04-15 09:13 UTC
Labels: Awaiting Information, ios, No Template

**Comment by japostigo-atsistemas** [comment] 2018-01-22 12:23
@rwillett Although the original poster didn't update the issue, I can confirm that the problem at present still persist.

**Comment by dielfilho** [comment] 2018-08-20 22:13
Any update on this issue?
