### ISSUE TITLE
Not getting notification on time in Android 6.0

### ISSUE THREAD

**Issue by shahbazcool98** [katzer/cordova-plugin-local-notifications#981] opened 2016-05-19 09:25 UTC
I am developing an cordova app for android. This plugin is working well in other android versions. But  in case of schedule `every: "week"` it is not working on time only in android marshmallow.

**Comment by andreyshedko** [comment] 2016-06-09 14:24
Same problem here - with this property set to "week" plugin not working correctly.

**Comment by andreyshedko** [comment] 2016-06-13 10:41
Anybody may advise solution?

**Comment by buguil** [comment] 2016-06-21 05:01
We are experiencing 4min delay in notification (at least in Marshmallow, we have to characterize more on other platforms).
Did you progress on that point ?

**Comment by shahbazcool98** [comment] 2016-07-07 07:52
Please check this
[Delay in notification fixed in Android M](http://stackoverflow.com/a/37349798/4685284)

**Comment by stevehanson** [comment] 2016-08-12 21:51
Is there a new build with this issue fixed? I'm also experiencing a several minute delay in receiving notifications, and I'm not sure how to implement the advice on the SO thread.

**Comment by rejhgadellaabsl** [comment] 2016-12-12 08:58
I once built a plugin for Cordova 2.7 that worked around this issue. I could pass it an argument ('exact') and it would use setExact() to set the alarm once. Then, when it fired, it checked if 'repeat' was true and re-set the schedule. SetExact() has been a thing since Android 4.4 or so but Marshmallow doubled down on that with its doze feature.

I had a quick look at the code in Notification.java and it looks like setExact is not implemented AT ALL in LocalNotification. Maybe do something about that, because Android is only going to be more strict about this. It's good to have it not-precise by default but sometimes one really needs a notif to fire at a exact time

**Comment by rwillett** [comment] 2017-02-27 09:38
This looks like an Android issue, not a issue with this plugin. Its explained in #938 

Am closing as its a not a bug here.

**Closed by rwillett** 2017-02-27 09:38 UTC
Labels: android
