### ISSUE TITLE
(void) update:- method is not working in ios10 branch of this plugin.

### ISSUE THREAD

**Issue by rameshsharmaaspire** [katzer/cordova-plugin-local-notifications#1271] opened 2017-04-14 08:56 UTC
**Issue** : Not able to update notification using update method of plugin in ios10.

**plugin link**:  https://github.com/katzer/cordova-plugin-local-notifications#ios10

**What I did to solve** : Uncommented commented code  below of update method in if condition of ios10 in **File :  APPLocalNotification.m** as it suppose to update notification in ios10. Uncommenting crashes app with error. 
      //           [self updateNotification:[notification copy]
     //                                     withOptions:options];
     //                        [self fireEvent:@"update" notification:notification];
     //                       if (notifications.count > 1) {
     //                          [NSThread sleepForTimeInterval:0.01];
     //                       }

**Error ?**  :  "**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UNNotificationRequest userInfo]: unrecognized selector sent to instance 0x174030f40**'"

**Example code :** 

//calling update in angular service file.

          window.cordova.plugins.notification.local.update({
                    id: optionsId,
                    title: attachmentObject.Name,
                   text: 'Download completed successfully.'/*,
                   icon: 'res://icon.png'
                  ,smallIcon:'res://icon.png'*/
                  },function (result) {
                  console.log('from local notification update ' + result); 
                 // coming Null
              });

  **File :  APPLocalNotification.m**
     **Method: update**

     //           [self updateNotification:[notification copy]
     //                                     withOptions:options];
     //                        [self fireEvent:@"update" notification:notification];
     //                       if (notifications.count > 1) {
     //                          [NSThread sleepForTimeInterval:0.01];
     //                       }

  why this code is commented here . as I guess it should be the main reason that update method is not working in ios10 as it is not call updateNotification method commented in above code.

schedule is working fine even click also but update is not working here.
 Please guide me to fix this or let me know if it is not covered in this plugin or anyone else has done same way and its working to them.I am actually not ios developer and has very less idea about objective C.

Anyone's help will be greatly appreciated and @katzer Thanks for such beautiful plugin.

Thanks.
Ramesh.

**Comment by rwillett** [comment] 2017-04-17 07:46
I would say that I've read this and I still have no idea what the problem is. It might be helpful to provide a simpler explanation of what you expect to happen, perhaps with simple examples.

**Comment by rameshsharmaaspire** [comment] 2017-04-17 08:40
I have updated my question with more details. Hope it will help.

Thanks.

On Apr 17, 2017 1:16 PM, "Rob Willett" <notifications@github.com> wrote:

I would say that I've read this and I still have no idea what the problem
is. It might be helpful to provide a simpler explanation of what you expect
to happen, perhaps with simple examples.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/katzer/cordova-plugin-local-notifications/issues/1271#issuecomment-294426116>,
or mute the thread

**Comment by rameshsharmaaspire** [comment] 2017-04-17 08:40
I also want to confirm has anyone here able to update notification with this plugin in ios10. Rest all working to me.

**Comment by playerx** [comment] 2017-04-27 07:03
+1 I've same issue in iOS10.

**Comment by extempl** [comment] 2017-05-30 15:20
AFAIU `ios10` branch is not stable yet, as it is pointed in the readme, so no reason to expect it to work properly out of the box until it is merged to `master`.

**Comment by rwillett** [comment] 2017-05-30 15:24
We use the IOS10 branch and the bits we use seem to be stable. We don't use update as we have no use case to do this. The fact that it is commented out indicates it probably doesn't work under IOS10 and therefore should not be used.

**Comment by katzer** [comment] 2017-10-31 10:39
The update methods is back with 0.9-beta

**Closed by katzer** 2017-10-31 10:39 UTC
Labels: ios, question
