### ISSUE TITLE
Unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by prevostc** [katzer/cordova-plugin-local-notifications#623] opened 2015-07-08 12:56 UTC
Devices: iphone 5 (iOS 8.3) and iphone 4 (iOS 8.3)
Software: Cordova 4.2.0, ionic 1.5.5
Error message: `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x16d7aae0'`
Source code:
```
- (UILocalNotification*) localNotificationWithId:(NSString*)id
{
    NSArray* notifications = self.localNotifications;

    for (UILocalNotification* notification in notifications)
    {
        if ([notification.options.id isEqualToString:id]) { /**  <=== Error here : SIGABRT **/
            return notification;
        }
    }

    return NULL;
}
```
Scenario: I try to cancel the id "1" but it does not exists. The app crashes.

**Comment by romainfrancez** [comment] 2015-07-22 14:38
notification.options.id was somehow an NSNumber

**Comment by romainfrancez** [comment] 2015-07-23 07:33
Issue should be closed as this commit 30f8f6aa8ec0392bd2b08e7bd2187bb17367b64a cast everything to int anyway

**Comment by KTachibanaM** [comment] 2015-08-12 05:52
Hi,

I am still getting crashes when I try to schedule an notification on iOS.

Cordova plugins:
de.appplant.cordova.plugin.local-notification 0.8.2dev "LocalNotification"
org.apache.cordova.device 0.3.0 "Device"
uk.co.whiteoctober.cordova.appversion 0.1.7 "AppVersion"

Xcode version:
6.4 (6E35b)

iOS version:
8.4

Stacktrace:
2015-08-11 22:46:12.592 SIF Assistant[2776:18284] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x7a859200
2015-08-11 22:46:12.593 SIF Assistant[2776:18284] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x7a859200'

**Comment by KTachibanaM** [comment] 2015-08-12 06:26
nvm, I got one of the parameters wrong when passing options from JS, "every" should be a String instead of a Number
Weirdly the wiki says "every" should be a String but it writes the default value looking like a Number so I put Number(0) as the default "every" value previously, causing the crash.

**Comment by dovtenenboim** [comment] 2015-12-07 06:47
I'm experiencing this very issue in ios-sim.
On app load it crashes and restarts in an endless loop with the exact same error.

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x16d7aae0'`

What is the solution moving forward without having to modify .m or .h files within Xcode?

**Comment by katzer** [comment] 2015-12-10 10:33
@dovtenenboim Could you please provide a code snippet to reproduce the crash.

**Closed** 2015-12-25 10:51 UTC
Labels: feedback, ios
