### ISSUE TITLE
notification clear when app close from home btn in android

### ISSUE THREAD

**Issue by ghost** [katzer/cordova-plugin-local-notifications#1658] opened 2018-08-08 10:30 UTC
notification clear when app close from home btn in android

* Plugin version: 0.9.0-beta.2
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Motorola - G5 s plus
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): 6.3.0* Plugin config

## Expected Behavior

LocalNotification should be not close when app close by home button in android

_Tell us what happens instead_

Loacl notification close whn app close

**Comment by Tawpie** [comment] 2018-08-08 15:19
@rajan2ram try beta.3

**Comment by hordesalik** [comment] 2018-09-14 09:09
@Tawpie it's not fixed in beta.3

**Comment by Tawpie** [comment] 2018-09-14 15:18
@ghost since the easy answer isn't the correct answer, can you be more descriptive with what you mean by your expected behavior "Local notification should not be **_close_**"? My expectations are that when the user hits the home button, the app and all of its windows will go away (close). Any notifications that were in the notification shade will also be cleared and will no longer appear in the notification shade. 

Can you be very specific about what are you wanting to happen? (for example: when the app is running and a local notification is displayed, when I hit the home button the local notification should _____________ )

**Comment by hordesalik** [comment] 2018-09-14 17:05
when the app is running and a local notification is displayed, when I hit the home button the local notification should still be visible. For example how it does Google drive when user is downloading file. 
Once download complete, notification added and it still visible even if user close Google drive application until it is clicked or dismissed manually. I expect the same behaviour. Maybe it can be configured with some params.

**Comment by Tawpie** [comment] 2018-09-14 17:09
ah. That simply won't happen. The phone's operating system (Android/iOS) controls what happens when the home button is tapped and there's nothing your app or its plugins can do to change that. Right now, mobile devices will close all windows associated with your app when you tap the home button.

**Comment by hordesalik** [comment] 2018-09-14 17:33
Hmmm. Maybe we should use push notifications instead...

**Comment by hordesalik** [comment] 2018-09-17 08:41
Accroding to Android [documentation](https://developer.android.com/training/notify-user/build-notification):

> A notification remains visible in the notification drawer until dismissed by the app or the user.

Is it not about local notifications? So maybee this is a cordova related problem, not the OS itself?

**Comment by rwillett** [comment] 2018-09-17 08:53
AFAIK the action of starting an app up removes all the notifications.  I know that when I send push notifications down to both IOS and Android, starting the app up OR resuming the app from the background means the notifications are removed. That's the action for OneSignal and PushWoosh.  We have always assumed that is the case and indeed we write code to reschedule notifications that we want the user to see.

**Comment by hordesalik** [comment] 2018-09-17 09:06
@rwillett yes, maybe when the app is starting it works so, but notification get removed once app getting to the background mode. That's the main problem.

**Comment by lokkeshjaya** [comment] 2019-02-27 05:30
This behavior might be seen when you use local notification plugin in combination with phonegap-push plugin. phonegap-plugin-push by default clear all pending notifications when the app go in pause. To fix this behavior, just set the clearNotifications to "false":

`var push = PushNotification.init({ android: { clearNotifications:"false" } });`

**Closed** 2024-09-26 20:34 UTC
