### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by katzer** [katzer/cordova-plugin-local-notifications#451] opened 2015-03-11 13:41 UTC
Dear Local-Notification community,

please make use of the following page to propose new feature requests. Once accepted they will be added to an own [wiki page](https://github.com/katzer/cordova-plugin-local-notifications/wiki/Feature-Requests) with further informations.

Thanks!

**Comment by Tawpie** [comment] 2015-03-11 15:00
I know t's already planned, but compatibility with Windows Phone 8.1 would save me from having to hire someone to write it! (hint hint)

**Comment by katzer** [comment] 2015-03-11 16:10
@Tawpie, hire use or donate for it!

**Comment by Tawpie** [comment] 2015-03-11 16:12
are you available to hire? We'd be more than happy to donate it!

**Comment by katzer** [comment] 2015-03-11 16:22
@Tawpie, yes of course - contract work or depend on how much the community does donate for a feature it will be added quicker or later.

**Comment by Tawpie** [comment] 2015-03-11 16:34
Thanks Sebastián.

I do need this sooner than later -- in a crude form (schedule, the on click callback and cancel) as a starter. Assuming you are available -- can you give me a back of the envelope estimate of contract cost and timeline? We're a US startup trying to port our iOS/Android app to WP8.1 and simply don't have the time to deal with the notification port to WP8.1. There's only 1 of me developing, and I'm having enough fun with just getting the app to work! The app we're trying to port is SmartQuit, currently available on the App Store and in Play--it has a lite version. If it works out, I'd want to get you started without delay!

Or, if you know anyone that might be interested in contract work  who's contact information you can share I'd appreciate that as well.

Best regards

Kim Hansen
CTO
2Morrow Inc.
+1 425.442.2756

**Comment by katzer** [comment] 2015-03-11 17:19
Thanks Tawpie, you can share my contact informations below with Mr. Hansen.
 <http://www.appplant.de/>		appPlant Werkstatt für mobile Software 
Sebastián Katzer - Geschäftsführer 
Tschaikowskistraße 2 04105 Leipzig 
katzer@appplant.de <mailto:katzer@appplant.de> | www.appplant.de <http://www.appplant.de/> 
T: +49 (341) 26 5310 02 <tel:+4934126531002> | M: +49 (157) 720 930 51 <tel:+4915772093051> | F: +49 (341) 33 96500 35 <tel:+49341339650035>

**Comment by axten** [comment] 2015-03-12 08:57
if possible, it would be nice to have amazon fire os support, 
thats android with some additions so it should not take a long time.

**Comment by katzer** [comment] 2015-03-14 11:51
@Tawpie, if you like please vote for that cordova-windows issue!
https://issues.apache.org/jira/browse/CB-8674

**Comment by MaZZly** [comment] 2015-03-16 15:38
[Crosswalk](https://crosswalk-project.org/) integration.
Crosswalk is quite important if you want any kind of performance on a Cordova project that is supposed to run on pre-lollipop android devices (There are also performance improvements in lollipop aswell but there the apps usually run quite smoothly)

Should not be too hard to make the compability as the main difference (AFAIK) is that it uses a different webView

**Issue** https://github.com/katzer/cordova-plugin-local-notifications/issues/426

**Comment by ratt** [comment] 2015-03-23 10:55
+1 crosswalk support

**Comment by krik** [comment] 2015-03-25 20:02
CrossWalk please :)

**Comment by DerGuteWolf** [comment] 2015-03-25 20:04
Could you support vibration esp on Android?

**Comment by DerGuteWolf** [comment] 2015-03-25 20:06
Are on Android the default RingtoneManager Sounds TYPE_ALARM, TYPE_NOTIFICATION and TYPE_RINGTONE still supported with 0.8.x?

**Comment by DanailMinchev** [comment] 2015-03-25 20:41
+1 for crosswalk support

**Comment by alexusdenisov** [comment] 2015-03-26 15:40
Do you plan to support optional actions that are displayed at the bottom of the notification?http://developer.android.com/design/patterns/notifications.html

**Comment by sergeh** [comment] 2015-03-26 18:50
+1 for crosswalk support

**Comment by boltex** [comment] 2015-03-26 21:45
+1 crosswalk

**Comment by volantes** [comment] 2015-03-27 16:50
+1 crosswalk would be awesome!

**Comment by joshbatchelor** [comment] 2015-03-30 08:44
+1 Crosswalk

**Comment by kiStephane** [comment] 2015-03-30 13:17
Hi. It would be great to be able to lauch the application when the notification is fired; add it as an option. I think it won't request to much work.

**Comment by invernizzie** [comment] 2015-04-03 05:10
+1 Crosswalk

**Comment by katzer** [comment] 2015-04-08 19:52
@DerGuteWolf, they have been removed. `TYPE_NOTIFICATION` is still the default sound.

**Comment by katzer** [comment] 2015-04-08 19:54
Re crosswalk, can somebody provide a plug&play project or a list of incompatibilities?

**Comment by joshbatchelor** [comment] 2015-04-08 20:05
@katzer Not sure if this will help, but here is the fork I made to be able to use the plugin. My use case is pretty simple, but I haven't had any problems.

https://github.com/joshbatchelor/cordova-plugin-local-notifications

**Comment by katzer** [comment] 2015-04-08 20:20
@joshbatchelor, thanks that helps

**Comment by carpiediem** [comment] 2015-04-09 07:32
It would be great to be able to send "multi-page" notifications to wearables, as described for Android [here](https://developer.android.com/training/wearables/notifications/pages.html).

**Comment by krik** [comment] 2015-04-09 09:35
@joshbatchelor Thanks a lot!

**Comment by ratt** [comment] 2015-04-09 09:49
@joshbatchelor <https://github.com/joshbatchelor> Awesome thanks!

**Comment by josmarycarrero** [comment] 2015-04-10 21:52
weekends and weekdays on schedule function

**Comment by carpiediem** [comment] 2015-04-13 04:05
To add to alexusdenisov's suggestion of action buttons, it would bre great if we could simply set the url of where the user should be sent when they click on the notification.  Right now it seems to take you to the most recent screen you've been on.

**Comment by armenbadalyan** [comment] 2015-04-13 14:39
+1 for "multi-page" notifications

**Comment by paulorcdo** [comment] 2015-04-15 00:08
Hello katzer first would like to congratulate you for the work. Sensational. I would like to question the role that schedule multiple reminders with predefined date. When is schedule only the last event is scheduled, the others are not. Wonder if this is a mistake or this functionality does not exist, I've tried many forms, looped in array in json and always happen that way.


          var now = new Date().getTime(),
                    _5_sec_from_now = new Date(now + 5 * 1000);
                    _10_sec_from_now = new Date(now + 10 * 1000);
                var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf';
                cordova.plugins.notification.local.schedule([{
                    id: 1,
                    title: 'Scheduled with delay',
                    text: 'Test Message 1',
                    at: _5_sec_from_now,
                    sound: sound       
                } , {
                    id: 2,
                    title: 'Scheduled with delay',
                    text: 'Test Message 2',
                    at: _10_sec_from_now,
                    sound: sound              
           }]);

**Comment by wworley** [comment] 2015-04-15 03:10
I think a much needed solution for those of us creating many notification would be to add the ability to "stack" notifications such as described in the below links

for non-wearables
http://developer.android.com/guide/topics/ui/notifiers/notifications.html

for wearables
https://developer.android.com/training/wearables/notifications/stacks.html

**Comment by beliz** [comment] 2015-04-16 07:53
+1 Crosswalk

**Comment by bjrnblm** [comment] 2015-04-16 13:12
+1 Crosswalk

**Comment by abdullasulaiman** [comment] 2015-04-17 12:50
is this supports big image option ????

**Comment by DanailMinchev** [comment] 2015-04-23 09:23
Apache Cordova Android 4.0.0 + Crosswalk support.

With latest version of [Cordova Android](http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html), I'm receiving same error like in Crosswalk and described it here: https://github.com/katzer/cordova-plugin-local-notifications/issues/426

**Comment by WaldoHatesYou** [comment] 2015-05-09 18:09
I can't seem to find this in the documentation so I'm going to assume it's not a feature. So, I was wondering if you could add the ability to set the priority of notifications to this library. Android specifically has this and I would like to use it.

**Comment by mansa-dev** [comment] 2015-05-12 04:43
+1 Crosswalk

**Comment by martinbrylski** [comment] 2015-05-13 10:23
+1 Crosswalk

**Comment by sonnylazuardi** [comment] 2015-05-14 23:50
+1 Crosswalk

**Comment by DarrylD** [comment] 2015-05-25 14:07
Crosswalk and have a notification permanent (similar to voice-mail notification)

**Comment by blukis** [comment] 2015-07-05 20:03
Is this plugin hosted on "plugins.cordova.io" somewhere?  I'd like to be able to use this plugin through phonegap build.

**Comment by DerGuteWolf** [comment] 2015-07-05 20:07
"plugins.cordova.io" is deprecated and will be read-only in 8 days, cf. http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html.

**Comment by behrad** [comment] 2015-07-06 11:42
+1

**Comment by blukis** [comment] 2015-07-07 02:48
For those like me who were confused about how to make this work in phonegap build, this seems to be the piece I was missing: http://phonegap.com/blog/2015/05/26/npm-plugins-available/

**Comment by Dineshrajaa** [comment] 2015-07-13 10:49
Kindly move this plugin as well as all the other cordova plugins which you have developed to npm repository :)

**Comment by Krysisx** [comment] 2015-07-13 19:36
please +1 crosswalk and moving to npm. Thanks

**Comment by andrewmilson** [comment] 2015-07-15 23:36
+1 for vibrate control support

**Comment by blukis** [comment] 2015-07-17 02:53
Guys, it's in npm already: https://www.npmjs.com/package/cordova-plugin-local-notifications

Devs, Thank you for creating the first cordova notifications plugin that really works!  (All the others I've tried failed to notify after the app was closed by android.)

#1 on my wish list is vibration control (vibrate disable).  Thanks!

**Comment by shprink** [comment] 2015-08-07 05:08
+1 crosswalk and moving to npm
thanks!

**Comment by jgillard** [comment] 2015-08-13 17:56
+1 actionable notifications

**Comment by malloc32** [comment] 2015-08-31 08:58
Can be useful add reject() to some promise to control errors... for example if yo try to delete a notification with a not numeric id -> application crash...

**Comment by JonathonDunford** [comment] 2015-09-02 21:19
Please let us disable vibration. Should be an easy fix.

**Comment by vilu** [comment] 2015-09-14 09:46
I ran into the issue where I wanted the local notifications to show while in the application. To achieve this I had to set the priority .setPriority(1) in Builder.java. If this is something that is needed by others I could come up with a PR to add that to Option.java and Builder.java, please let me know if you want me to help.

**Comment by NickAjderian** [comment] 2015-10-13 13:20
Has Cordova 5.3.3 broken this plugin?
...\plugin\localnotification\LocalNotification.java:564: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
...\plugin\localnotification\LocalNotification.java:561: error: cannot find symbol
        webView.post(new Runnable(){
               ^
C:\...> cordova -v = 5.3.3

C:\...> cordova platform version android
Installed platforms: android 4.1.1, ios 3.9.1, windows

**Comment by programadormx** [comment] 2015-11-02 21:41
good day
As I do so that I can rather than a notification message is displayed.
The app is opened when closed

Thank you

**Comment by DanailMinchev** [comment] 2015-11-03 11:30
Publish to npmjs.com (officially), please.

Not sure which of them to use:
https://www.npmjs.com/search?q=cordova-plugin-local-notifications

https://github.com/katzer/cordova-plugin-local-notifications/issues/586
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

Thank you!

**Comment by programadormx** [comment] 2015-11-07 00:24
..........................new notification............
cordova.plugins.notification.local.schedule({
                          id         : 1,
                          title      : 'Transacciones',
                          text       : 'transacciones automaticas ',
                          sound      : null,
                          every      : '3',
                          autoClear  : false
                        });

cordova.plugins.notification.local.on("trigger", function (notification) {
           //run my code


        });

So far so good, as long as the application is open.
Notification correctly I run every 3 minutes.

The problem is that if I close or kill the app, notifications are still operating but already I can not run the trigger method.

I need you to kill the application but continue to operate the trigger method

Thank you

**Comment by invernizzie** [comment] 2015-11-07 15:29
@programadormx este no es el lugar para reportar problemas. Aquí solo pedimos funcionalidad que quisiéramos que forme parte del plugin.

Por favor, crea otro issue para resolver tus inconvenientes o reportar bugs. Saludos.

@katzer it might be a good idea to create a gitter.im room for people to discuss their experiences with the plugin and ask for help without cluttering GitHub issues.

**Comment by liuzhen2008** [comment] 2015-11-20 15:48
@carpiediem +1 for buttons

**Comment by katzer** [comment] 2015-12-09 17:13
Buttons are coming with v0.9. To get a foretaste see #774

**Comment by nursyafiah** [comment] 2016-01-04 03:03
hi katzer, is it possible for the notification to notify the user on every beacon detection, even when the app is swipe away from the recent list (not force close)?

**Comment by joakimmelkersson** [comment] 2016-01-05 08:24
Great plugin, really makes getting scheduled local notifications into your Cordova app a breeze! However, here are a few features I think would make the notifications a lot nicer:

1. Allow for only `smallIcon` to be set (which in native Android code would make it appear both in the status bar and next to the notification). Currently it seems like `largeIcon` is always set to a default, even if you null it.
2. Rename `icon` to `largeIcon`, to correspond with the [native API](http://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html) names. Actually, this would be a good change for everything where it makes sense (for example, `contentTitle` and `contentText` instead of the current `title` and `text`). This would make it easier to understand what in the plugin API corresponds to what in the native API, especially if you're already familiar with how notifications work in native code.
3. Auto-scale `largeIcon` (if set) to the proper size, or at least provide an option to do so. Currently an image that's too small will look very small, etc.
4. Provide option to make `largeIcon` circular even if a rectangular asset is provided.
5. Allow for expandable notifications. It wouldn't have to be very advanced initally, but without this option it's impossible to show more than a single line of text in a notification. The easiest way to implement this would probably be using [NotificationCompat.BigTextStyle](http://developer.android.com/reference/android/support/v4/app/NotificationCompat.BigTextStyle.html).

**Comment by jim0020** [comment] 2016-01-12 16:35
Allow repeating notifications with custom 'every' intervals, like every 30 minutes, or every 6 months

**Comment by alanvido** [comment] 2016-02-05 13:44
I want to work with the support of big text notifications for android, I have the code but do not know how to add it to your project if you are interested in adding this new feature just give me a branch 

best regards

**Comment by harlemblues** [comment] 2016-02-21 08:36
I need to schedule a notification on a daily basis but only during the 5 working days of the week (Sat and Sun excluded). Or is this perhaps already possible?

**Comment by midhunadarvin** [comment] 2016-03-25 07:12
Show a progress bar in the notification --> #850

**Comment by r3trosteve** [comment] 2016-04-11 11:54
Are we able to use Notification Actions for iOS or Android?

**Comment by harlemblues** [comment] 2016-04-11 14:39
Oh yes, thank you for checking. I studied the documentation more carefully
and was able to achieve my goal.

*Lorenzo Ciaravola*

**Comment by polarsbear** [comment] 2016-07-17 08:00
is heads-up notifications already supported?

**Comment by saurabhvyas** [comment] 2016-08-02 16:17
Can you please add image support in push notifications ?

**Comment by billycomic** [comment] 2016-09-09 13:41
I might have missed this in some buried documentation somewhere. Is it possible to setup a way to select a specific time, on different days of the week? For example, a user wants a notification at 9:00am, but they want to get that message every Monday, Wednesday, and Friday. How would I implement this?

**Comment by sahildaga95** [comment] 2016-10-05 05:21
Is the plugin fully compatible with Ionic 2. i have opened an issue https://github.com/katzer/cordova-plugin-local-notifications/issues/972 here and i just wanted to know when will you be updating to support Ionic 2 ?

**Comment by daniele-sartiano** [comment] 2016-10-29 08:01
Is there the way to delete a notification before this is visible?

**Comment by B00268219** [comment] 2016-12-18 21:10
Can this plugin update the notification at the time its captured by the trigger event?
, i tried the following......
cordova.plugins.notification.local.on("trigger", function(notification).....
 cordova.plugins.notification.local.update({...........}}

but before this function is completely executed, the notification has been sent to the notification center
and shows as expired.

Local storage contains contains the update, possibly a method/function to verify the notification before sending would be helpful idk, does one exist? cant find an example or anything in the docs?

**Comment by esmiralha** [comment] 2017-01-13 13:14
There is a pull request for multi line notifications pending review. Please review and accept it. Currently the plugin is unusable except for very simple notifications.

**Comment by harleybl** [comment] 2017-04-25 02:14
Similar to B00268219.. 
It would be great if there were a pre-trigger event that fired that one could subscribe to.
This would allow for the opportunity to cancel or change the event notification before it is displayed to the user.

**Comment by kennrll18** [comment] 2017-06-19 08:52
Can you guys add an option to launch the app when the app is force closed?

**Comment by FrancescoMussi** [comment] 2017-07-10 09:19
Agree very much with @joakimmelkersson feature request n. 5 for expandable notifications.

The title I need to include there often are slightly longer than one line.
It would be a great feature.

**Comment by cdpconsulting** [comment] 2017-07-17 01:07
An option for having the device notification led blink would be important for us to be able to use this plugin. Is this something already implemented just maybe I am not seeing how to set the option? Or is this already under consideration? (Behavior would be similar to when user gets a text message or email and the led light is blinking until the notification is read)

**Comment by Tawpie** [comment] 2017-07-17 02:16
The led does blink, and on Android you can set the color as well... the flash cannot be made to blink with this plugin.

(spelling and grammer powered by autocorrupt)

**Comment by d3w201** [comment] 2017-07-18 09:14
dear developers, first compliments for your great works!
second.. is possible to set the notification remotely? i know this is probably a stupid question because the name of the plugin is "LOCAL"-notification , but anyway i ask because i am a monkey in dna...

**Comment by anibalcesar** [comment] 2017-08-10 19:52
cordova-browser support

**Comment by chpecson** [comment] 2017-09-18 03:54
+1 for vibrate control support

**Comment by sbannigan** [comment] 2018-01-25 03:11
Any plans to add Android support for Location based notifications?

**Comment by gokulm** [comment] 2018-01-25 13:33
Is it possible to add media controls (play/pause/skip etc.,) with all the existing properties and make it work like this plugin https://github.com/homerours/cordova-music-controls-plugin (this isn't working in the latest android devices) ?

**Comment by katzer** [comment] 2018-02-05 09:54
@sbannigan Location based notifications aren't in the plan yet or will be available with 0.9.0. However since they are supported already for iOS its also intended to be supported with a future version of 0.9.x

**Comment by katzer** [comment] 2018-02-05 09:56
browser support will also come in future. Usually I would add with 0.9.0. But I think to add it later otherwise it will take even longer to release the next stable version.

**Comment by katzer** [comment] 2018-02-05 10:05
@gokulm The plugin supports the android[media style ](https://developer.android.com/reference/android/app/Notification.MediaStyle.html). However than hasn't been tested yet. Thats why its also not mentioned on the README.

**Comment by gokulm** [comment] 2018-02-08 13:40
@katzer could you please tell how mediasession can be created and used with this plugin? also, does the media style work only for android?

**Comment by gokulm** [comment] 2018-02-13 10:56
@katzer done https://github.com/katzer/cordova-plugin-local-notifications/issues/1532

**Comment by abood91** [comment] 2018-03-04 12:54
@katzer  Is it possible to include a property that will make the notification sound play forever until its cleared or canceled ? (not only seen ) something to replicate the behavior of alarm clock basically 

**cheers !**

**Comment by HugoHeneault** [comment] 2018-03-05 16:50
@abood91 You might want to repeat the notification with a value of the time of the sound?

**Comment by abood91** [comment] 2018-03-05 20:11
@HugoHeneault, what do you mean ? 

I think notification has limited on time (30) seconds and if your sound tone runs for more then that the you might repeat the first 30 sec. Over and over again ... ?

**Comment by HugoHeneault** [comment] 2018-03-06 09:08
@abood91 Have a look here: https://github.com/katzer/cordova-plugin-local-notifications#repeating

**Comment by abood91** [comment] 2018-03-06 18:31
@HugoHeneault I did but could you provide a sample code example where notification plays sound app is launched / interacted with, basically as I said am looking to replicate alarm app functionality (maybe other plugin ?) 

Cheers

**Comment by davidecantini** [comment] 2018-03-15 11:50
Feature: **enable a notification to be triggered only if a (dynamic) condition is true**.

In some cases, scheduling a notification to occur unconditionally (e.g. every day at noon time) may result in a bad user experience. For example, nobody would like to see a notification that says "Hey, there's nothing new today": some (or most) users go like "hey, if there's nothing new, then don't bother me!". That disappointment is understandable because we're all too busy to get distracted by meaningless notifications. So, if properly used, this feature would help app developers to provide a better user experience.
p.s. I this this was also requested [here](https://github.com/katzer/cordova-plugin-local-notifications/issues/972).

**Comment by jringbox** [comment] 2020-04-28 13:09
How about a way for the plugin to detect if the privacy settings for notifications are "hidden" or not on Android (not sure if iOS has this option)?  I have a requirement where sensitive information should not be in the notification on the phone's lock screen if notification is not set to hidden.  If the phone is not set to hidden then, it display a simple notification message.  If it is set to hidden, then it shows detailed notification messages as normal.  Is this something that could be planned a new feature soon?

**Closed** 2024-09-26 20:35 UTC
Labels: enhancement
