### ISSUE TITLE
Adding new Local Notification crashes app (iOS8)

### ISSUE THREAD

**Issue by yourbuddyconner** [katzer/cordova-plugin-local-notifications#309] opened 2014-11-05 18:47 UTC
I've been trying to get Local Notifications to work within an Ionic app, however I've hit a roadblock. Originally, I was using ngCordova to encapsulate the functionality of this plugin, but due to the recent update I'm accessing the plugin directly. 

I've got an angular controller: 
```
.controller('EventsCtrl', function($scope, $ionicPlatform, $window, $cordovaLocalNotification, $cordovaDialogs) {
    $scope.setReminder = function() {
        $ionicPlatform.ready(function () {
            $window.plugin.notification.local.add({
                id:         "1",  // A unique id of the notification
                date:       new Date(),    // This expects a date object
                message:    "yolo",  // The message
                title:      "Stop Yoloing.",  // The title of the message
                badge:      1,  // Displays a numerical badge
                autoCancel: false, // The notification is canceled when the user clicks it
            });
        });
    };
```

Basically, in the view when a button is clicked it calls $scope.setReminder which in turn calls window.plugin.notification.local.add(), pretty simple. 

However, when this is run it throws a low-level ObjC error: 
```
Nov  5 11:41:08 Democritus.PK5001Z rtcreporting[98570] <Info>: logging starts...
Nov  5 11:41:08 Democritus.PK5001Z rtcreporting[98570] <Debug>: setMessageLoggingBlock: called
2014-11-05 11:41:21.391 KJACK[98570:605974] ready!
2014-11-05 11:41:21.393 KJACK[98570:606049] -[__NSCFString stringValue]: unrecognized selector sent to instance 0x7a7a9590
2014-11-05 11:41:21.394 KJACK[98570:606049] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString stringValue]: unrecognized selector sent to instance 0x7a7a9590'
*** First throw call stack:
(
	0   CoreFoundation                      0x0028ddf6 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x0280ea97 objc_exception_throw + 44
	2   CoreFoundation                      0x00295a75 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
	3   CoreFoundation                      0x001de9c7 ___forwarding___ + 1047
	4   CoreFoundation                      0x001de58e _CF_forwarding_prep_0 + 14
	5   KJACK                               0x000aeb77 -[APPLocalNotification notificationWithId:] + 503
	6   KJACK                               0x000ae906 -[APPLocalNotification isNotificationScheduledWithId:] + 86
	7   KJACK                               0x000aaf2f __28-[APPLocalNotification add:]_block_invoke + 207
	8   libdispatch.dylib                   0x02ea1b4a _dispatch_call_block_and_release + 15
	9   libdispatch.dylib                   0x02ebe03f _dispatch_client_callout + 14
	10  libdispatch.dylib                   0x02ea8a6c _dispatch_root_queue_drain + 475
	11  libdispatch.dylib                   0x02ea999d _dispatch_worker_thread3 + 108
	12  libsystem_pthread.dylib             0x03213296 _pthread_wqthread + 724
	13  libsystem_pthread.dylib             0x03210eea start_wqthread + 30
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Any ideas as to why this occurs? I don't think it's my JS code, but I could be wrong.

**Comment by davidpfahler** [comment] 2015-01-09 13:05
@jgberg I think the issue is simply that the latest stable version does [not include the fix](https://github.com/katzer/cordova-plugin-local-notifications/blob/0.7.7/src/ios/APPLocalNotification.m#L582-L583), right? People just prefer to use something called "stable" instead of using the master.

**Comment by jgberg** [comment] 2015-01-09 17:11
Yes that's right. The latest 0.7.7 I believe and it must be patched.

**Comment by katzer** [comment] 2015-01-11 16:39
Hey, I have pushed the fix now (v0.7.8, db4b0a28bf8ad4f33e59fb91153102c7fb497719). Somehow the commit was not included in v0.7.7.

**Comment by katzer** [comment] 2015-03-11 12:46
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Closed by katzer** 2015-03-11 12:46 UTC

**Comment by bonlemuel** [comment] 2016-08-05 02:51
I've posted an issue. I was not successful even when applying the said solutions:

https://github.com/katzer/cordova-plugin-local-notifications/issues/1062

**Comment by Tawpie** [comment] 2016-08-05 03:03
Try it with the id as an int.

**Comment by bonlemuel** [comment] 2016-08-05 03:07
@Tawpie I'm sorry. But how will I do that? :|

**Comment by bonlemuel** [comment] 2016-08-05 03:08
@Tawpie I think I get it.

**Comment by bonlemuel** [comment] 2016-08-05 03:13
@Tawpie Thanks Man! It solves the issue.

**Comment by Tawpie** [comment] 2016-08-05 03:32
Glad to help!
  
  
 (grammar and spelling mostly courtesy of autocorrupt)  
  
  

  
  
  
  

  
  
>
